import { buildCuratedCategory, type CuratedFact } from "./_builder";

/* ── Easy (Argent · 1000 ELO) ─────────────────────────────────────── */
const easy: CuratedFact[] = [
  // Films / réalisateurs (10)
  ["Qui a réalisé Pulp Fiction ?", "Who directed Pulp Fiction?", "Quentin Tarantino", "Quentin Tarantino", ["Martin Scorsese", "Steven Spielberg", "Francis Ford Coppola"], ["Martin Scorsese", "Steven Spielberg", "Francis Ford Coppola"]],
  ["Qui a réalisé Titanic ?", "Who directed Titanic?", "James Cameron", "James Cameron", ["Steven Spielberg", "Ridley Scott", "Peter Jackson"], ["Steven Spielberg", "Ridley Scott", "Peter Jackson"]],
  ["Qui a réalisé Avatar ?", "Who directed Avatar?", "James Cameron", "James Cameron", ["Peter Jackson", "Ridley Scott", "George Lucas"], ["Peter Jackson", "Ridley Scott", "George Lucas"]],
  ["Qui a créé la saga Star Wars ?", "Who created Star Wars?", "George Lucas", "George Lucas", ["Steven Spielberg", "James Cameron", "Ridley Scott"], ["Steven Spielberg", "James Cameron", "Ridley Scott"]],
  ["Qui a réalisé Le Parrain ?", "Who directed The Godfather?", "Francis Ford Coppola", "Francis Ford Coppola", ["Martin Scorsese", "Steven Spielberg", "Stanley Kubrick"], ["Martin Scorsese", "Steven Spielberg", "Stanley Kubrick"]],
  ["Qui a réalisé E.T. l'extra-terrestre ?", "Who directed E.T.?", "Steven Spielberg", "Steven Spielberg", ["George Lucas", "James Cameron", "Robert Zemeckis"], ["George Lucas", "James Cameron", "Robert Zemeckis"]],
  ["Qui a réalisé Inception ?", "Who directed Inception?", "Christopher Nolan", "Christopher Nolan", ["David Fincher", "Denis Villeneuve", "Ridley Scott"], ["David Fincher", "Denis Villeneuve", "Ridley Scott"]],
  ["Qui a réalisé Forrest Gump ?", "Who directed Forrest Gump?", "Robert Zemeckis", "Robert Zemeckis", ["Steven Spielberg", "Ron Howard", "Tom Hanks"], ["Steven Spielberg", "Ron Howard", "Tom Hanks"]],
  ["Qui a réalisé Le Seigneur des anneaux ?", "Who directed The Lord of the Rings?", "Peter Jackson", "Peter Jackson", ["James Cameron", "George Lucas", "Ridley Scott"], ["James Cameron", "George Lucas", "Ridley Scott"]],
  ["Qui a réalisé Jurassic Park ?", "Who directed Jurassic Park?", "Steven Spielberg", "Steven Spielberg", ["George Lucas", "James Cameron", "Ron Howard"], ["George Lucas", "James Cameron", "Ron Howard"]],
  // Acteurs (10)
  ["Qui joue Forrest dans Forrest Gump ?", "Who plays Forrest in Forrest Gump?", "Tom Hanks", "Tom Hanks", ["Tom Cruise", "Brad Pitt", "Kevin Costner"], ["Tom Cruise", "Brad Pitt", "Kevin Costner"]],
  ["Qui joue Jack Sparrow dans Pirates des Caraïbes ?", "Who plays Jack Sparrow in Pirates of the Caribbean?", "Johnny Depp", "Johnny Depp", ["Orlando Bloom", "Brad Pitt", "Christian Bale"], ["Orlando Bloom", "Brad Pitt", "Christian Bale"]],
  ["Qui joue Iron Man ?", "Who plays Iron Man?", "Robert Downey Jr.", "Robert Downey Jr.", ["Chris Evans", "Mark Ruffalo", "Tom Holland"], ["Chris Evans", "Mark Ruffalo", "Tom Holland"]],
  ["Qui joue Ethan Hunt dans Mission Impossible ?", "Who plays Ethan Hunt in Mission: Impossible?", "Tom Cruise", "Tom Cruise", ["Brad Pitt", "Matt Damon", "Daniel Craig"], ["Brad Pitt", "Matt Damon", "Daniel Craig"]],
  ["Qui joue James Bond dans Skyfall ?", "Who plays James Bond in Skyfall?", "Daniel Craig", "Daniel Craig", ["Pierce Brosnan", "Sean Connery", "Roger Moore"], ["Pierce Brosnan", "Sean Connery", "Roger Moore"]],
  ["Qui joue Léon dans Léon ?", "Who plays Léon in Léon?", "Jean Reno", "Jean Reno", ["Vincent Cassel", "Mathieu Kassovitz", "Daniel Auteuil"], ["Vincent Cassel", "Mathieu Kassovitz", "Daniel Auteuil"]],
  ["Qui joue Driss dans Intouchables ?", "Who plays Driss in The Intouchables?", "Omar Sy", "Omar Sy", ["Jamel Debbouze", "Vincent Cassel", "Tahar Rahim"], ["Jamel Debbouze", "Vincent Cassel", "Tahar Rahim"]],
  ["Qui joue le Joker en 2019 ?", "Who played the Joker in 2019?", "Joaquin Phoenix", "Joaquin Phoenix", ["Heath Ledger", "Jared Leto", "Jack Nicholson"], ["Heath Ledger", "Jared Leto", "Jack Nicholson"]],
  ["Qui joue Rocky Balboa ?", "Who plays Rocky Balboa?", "Sylvester Stallone", "Sylvester Stallone", ["Arnold Schwarzenegger", "Bruce Willis", "Jean-Claude Van Damme"], ["Arnold Schwarzenegger", "Bruce Willis", "Jean-Claude Van Damme"]],
  ["Qui joue Jack dans Titanic ?", "Who plays Jack in Titanic?", "Leonardo DiCaprio", "Leonardo DiCaprio", ["Brad Pitt", "Tom Cruise", "Matt Damon"], ["Brad Pitt", "Tom Cruise", "Matt Damon"]],
  // Séries TV (8)
  ["Qui a créé Breaking Bad ?", "Who created Breaking Bad?", "Vince Gilligan", "Vince Gilligan", ["David Chase", "David Simon", "Matthew Weiner"], ["David Chase", "David Simon", "Matthew Weiner"]],
  ["Quel auteur a écrit la saga Game of Thrones ?", "Who wrote the Game of Thrones books?", "George R. R. Martin", "George R. R. Martin", ["J. R. R. Tolkien", "Brandon Sanderson", "Robert Jordan"], ["J. R. R. Tolkien", "Brandon Sanderson", "Robert Jordan"]],
  ["Combien de saisons compte la série Friends ?", "How many seasons does Friends have?", "10", "10", ["8", "9", "12"], ["8", "9", "12"]],
  ["Quelle ville sert de cadre principal à The Office (US) ?", "Where is The Office (US) set?", "Scranton", "Scranton", ["New York", "Chicago", "Boston"], ["New York", "Chicago", "Boston"]],
  ["Dans quelle ville se déroule Stranger Things ?", "Where is Stranger Things set?", "Hawkins", "Hawkins", ["Salem", "Riverdale", "Derry"], ["Salem", "Riverdale", "Derry"]],
  ["Sur quelle île se déroule la série Lost ?", "Where is Lost set?", "Une île mystérieuse", "A mysterious island", ["Hawaï", "Madagascar", "Une station spatiale"], ["Hawaii", "Madagascar", "A space station"]],
  ["Qui joue le rôle principal de Dr House ?", "Who plays Dr. House?", "Hugh Laurie", "Hugh Laurie", ["Bryan Cranston", "Kiefer Sutherland", "Mandy Patinkin"], ["Bryan Cranston", "Kiefer Sutherland", "Mandy Patinkin"]],
  ["Quelle série espagnole a pour titre original La Casa de Papel ?", "Which series is titled La Casa de Papel originally?", "La Casa de Papel", "Money Heist", ["Élite", "Narcos", "Vis a vis"], ["Elite", "Narcos", "Locked Up"]],
  // Musique pop / rock (10)
  ["Dans quelle ville le groupe les Beatles s'est-il formé ?", "In which city were the Beatles formed?", "Liverpool", "Liverpool", ["Londres", "Manchester", "Birmingham"], ["London", "Manchester", "Birmingham"]],
  ["Quel groupe a chanté Bohemian Rhapsody ?", "Who sang Bohemian Rhapsody?", "Queen", "Queen", ["The Beatles", "Led Zeppelin", "Pink Floyd"], ["The Beatles", "Led Zeppelin", "Pink Floyd"]],
  ["Qui a chanté Thriller ?", "Who sang Thriller?", "Michael Jackson", "Michael Jackson", ["Prince", "Stevie Wonder", "Lionel Richie"], ["Prince", "Stevie Wonder", "Lionel Richie"]],
  ["Qui a écrit la chanson Yesterday ?", "Who wrote Yesterday?", "Paul McCartney", "Paul McCartney", ["John Lennon", "George Harrison", "Ringo Starr"], ["John Lennon", "George Harrison", "Ringo Starr"]],
  ["Qui a chanté Like a Virgin ?", "Who sang Like a Virgin?", "Madonna", "Madonna", ["Whitney Houston", "Cyndi Lauper", "Tina Turner"], ["Whitney Houston", "Cyndi Lauper", "Tina Turner"]],
  ["Qui a chanté Imagine ?", "Who sang Imagine?", "John Lennon", "John Lennon", ["Paul McCartney", "Bob Dylan", "Elton John"], ["Paul McCartney", "Bob Dylan", "Elton John"]],
  ["Qui a chanté Despacito ?", "Who sang Despacito?", "Luis Fonsi", "Luis Fonsi", ["Daddy Yankee", "Enrique Iglesias", "Shakira"], ["Daddy Yankee", "Enrique Iglesias", "Shakira"]],
  ["Qui a chanté Rolling in the Deep ?", "Who sang Rolling in the Deep?", "Adele", "Adele", ["Beyoncé", "Rihanna", "Lady Gaga"], ["Beyoncé", "Rihanna", "Lady Gaga"]],
  ["Quel groupe britannique a chanté Hotel California ?", "Who sang Hotel California?", "Eagles", "Eagles", ["Fleetwood Mac", "Pink Floyd", "Led Zeppelin"], ["Fleetwood Mac", "Pink Floyd", "Led Zeppelin"]],
  ["Qui a chanté Single Ladies ?", "Who sang Single Ladies?", "Beyoncé", "Beyoncé", ["Rihanna", "Mariah Carey", "Christina Aguilera"], ["Rihanna", "Mariah Carey", "Christina Aguilera"]],
  // Livres / BD (5)
  ["Qui a écrit Le Petit Prince ?", "Who wrote The Little Prince?", "Saint-Exupéry", "Saint-Exupéry", ["Albert Camus", "Marcel Proust", "Jean-Paul Sartre"], ["Albert Camus", "Marcel Proust", "Jean-Paul Sartre"]],
  ["Qui a écrit Harry Potter ?", "Who wrote Harry Potter?", "J. K. Rowling", "J. K. Rowling", ["C. S. Lewis", "Roald Dahl", "Philip Pullman"], ["C. S. Lewis", "Roald Dahl", "Philip Pullman"]],
  ["Qui a écrit 1984 ?", "Who wrote 1984?", "George Orwell", "George Orwell", ["Aldous Huxley", "Ray Bradbury", "Philip K. Dick"], ["Aldous Huxley", "Ray Bradbury", "Philip K. Dick"]],
  ["Qui a dessiné Tintin ?", "Who created Tintin?", "Hergé", "Hergé", ["Goscinny", "Uderzo", "Franquin"], ["Goscinny", "Uderzo", "Franquin"]],
  ["Qui a scénarisé Astérix avec Uderzo ?", "Who co-wrote Asterix with Uderzo?", "René Goscinny", "René Goscinny", ["Hergé", "Morris", "André Franquin"], ["Hergé", "Morris", "André Franquin"]],
  // Misc culture pop (7)
  ["Quelle entreprise a créé Mario ?", "Which company created Mario?", "Nintendo", "Nintendo", ["Sega", "Sony", "Atari"], ["Sega", "Sony", "Atari"]],
  ["Quelle entreprise a créé Sonic ?", "Which company created Sonic?", "Sega", "Sega", ["Nintendo", "Sony", "Capcom"], ["Nintendo", "Sony", "Capcom"]],
  ["Quel studio a produit Toy Story ?", "Which studio produced Toy Story?", "Pixar", "Pixar", ["DreamWorks", "Disney Animation", "Blue Sky"], ["DreamWorks", "Disney Animation", "Blue Sky"]],
  ["Qui a créé Mickey Mouse ?", "Who created Mickey Mouse?", "Walt Disney", "Walt Disney", ["Tex Avery", "William Hanna", "Joseph Barbera"], ["Tex Avery", "William Hanna", "Joseph Barbera"]],
  ["Quel cinéma indien produit le plus de films ?", "Which Indian film industry produces the most films?", "Bollywood", "Bollywood", ["Tollywood", "Kollywood", "Mollywood"], ["Tollywood", "Kollywood", "Mollywood"]],
  ["Quel film de 2019 a remporté la Palme d'or ?", "Which 2019 film won the Palme d'Or?", "Parasite", "Parasite", ["Once Upon a Time in Hollywood", "Joker", "Le Traître"], ["Once Upon a Time in Hollywood", "Joker", "The Traitor"]],
  ["Quel film a remporté l'Oscar du meilleur film en 2020 ?", "Which film won Best Picture at the 2020 Oscars?", "Parasite", "Parasite", ["1917", "Joker", "Once Upon a Time in Hollywood"], ["1917", "Joker", "Once Upon a Time in Hollywood"]],
];

/* ── Medium (Or · 1400 ELO) ───────────────────────────────────────── */
const medium: CuratedFact[] = [
  // Réalisateurs / films classiques (10)
  ["Qui a réalisé Citizen Kane ?", "Who directed Citizen Kane?", "Orson Welles", "Orson Welles", ["John Ford", "Howard Hawks", "Frank Capra"], ["John Ford", "Howard Hawks", "Frank Capra"]],
  ["Qui a réalisé Vertigo ?", "Who directed Vertigo?", "Alfred Hitchcock", "Alfred Hitchcock", ["Orson Welles", "Billy Wilder", "John Ford"], ["Orson Welles", "Billy Wilder", "John Ford"]],
  ["Qui a réalisé 2001 l'Odyssée de l'espace ?", "Who directed 2001: A Space Odyssey?", "Stanley Kubrick", "Stanley Kubrick", ["Steven Spielberg", "Ridley Scott", "George Lucas"], ["Steven Spielberg", "Ridley Scott", "George Lucas"]],
  ["Qui a réalisé Apocalypse Now ?", "Who directed Apocalypse Now?", "Francis Ford Coppola", "Francis Ford Coppola", ["Martin Scorsese", "Stanley Kubrick", "Brian De Palma"], ["Martin Scorsese", "Stanley Kubrick", "Brian De Palma"]],
  ["Qui a réalisé La Liste de Schindler ?", "Who directed Schindler's List?", "Steven Spielberg", "Steven Spielberg", ["Roman Polanski", "Martin Scorsese", "Stanley Kubrick"], ["Roman Polanski", "Martin Scorsese", "Stanley Kubrick"]],
  ["Qui a réalisé Reservoir Dogs ?", "Who directed Reservoir Dogs?", "Quentin Tarantino", "Quentin Tarantino", ["Robert Rodriguez", "Wes Anderson", "Sam Raimi"], ["Robert Rodriguez", "Wes Anderson", "Sam Raimi"]],
  ["Qui a réalisé La Dolce Vita ?", "Who directed La Dolce Vita?", "Federico Fellini", "Federico Fellini", ["Vittorio De Sica", "Roberto Rossellini", "Pier Paolo Pasolini"], ["Vittorio De Sica", "Roberto Rossellini", "Pier Paolo Pasolini"]],
  ["Qui a réalisé Le Septième Sceau ?", "Who directed The Seventh Seal?", "Ingmar Bergman", "Ingmar Bergman", ["Lars von Trier", "Carl Dreyer", "Andrei Tarkovski"], ["Lars von Trier", "Carl Dreyer", "Andrei Tarkovsky"]],
  ["Qui a réalisé Les Sept Samouraïs ?", "Who directed Seven Samurai?", "Akira Kurosawa", "Akira Kurosawa", ["Yasujirō Ozu", "Kenji Mizoguchi", "Hayao Miyazaki"], ["Yasujirō Ozu", "Kenji Mizoguchi", "Hayao Miyazaki"]],
  ["Qui a réalisé Roma (2018) ?", "Who directed Roma (2018)?", "Alfonso Cuarón", "Alfonso Cuarón", ["Guillermo del Toro", "Alejandro González Iñárritu", "Pedro Almodóvar"], ["Guillermo del Toro", "Alejandro González Iñárritu", "Pedro Almodóvar"]],
  // Acteurs récompenses (10)
  ["Qui a remporté l'Oscar du meilleur acteur pour There Will Be Blood ?", "Best Actor Oscar winner for There Will Be Blood?", "Daniel Day-Lewis", "Daniel Day-Lewis", ["Joaquin Phoenix", "Leonardo DiCaprio", "Sean Penn"], ["Joaquin Phoenix", "Leonardo DiCaprio", "Sean Penn"]],
  ["Qui a remporté l'Oscar pour Le Discours d'un roi ?", "Best Actor Oscar winner for The King's Speech?", "Colin Firth", "Colin Firth", ["Christian Bale", "Jeff Bridges", "Jeremy Renner"], ["Christian Bale", "Jeff Bridges", "Jeremy Renner"]],
  ["Qui a remporté l'Oscar pour American Beauty ?", "Best Actor Oscar winner for American Beauty?", "Kevin Spacey", "Kevin Spacey", ["Russell Crowe", "Tom Hanks", "Denzel Washington"], ["Russell Crowe", "Tom Hanks", "Denzel Washington"]],
  ["Qui a remporté l'Oscar pour The Revenant ?", "Best Actor Oscar winner for The Revenant?", "Leonardo DiCaprio", "Leonardo DiCaprio", ["Matt Damon", "Eddie Redmayne", "Bryan Cranston"], ["Matt Damon", "Eddie Redmayne", "Bryan Cranston"]],
  ["Qui a remporté l'Oscar de la meilleure actrice pour Black Swan ?", "Best Actress Oscar winner for Black Swan?", "Natalie Portman", "Natalie Portman", ["Annette Bening", "Michelle Williams", "Nicole Kidman"], ["Annette Bening", "Michelle Williams", "Nicole Kidman"]],
  ["Qui a remporté l'Oscar pour La Môme ?", "Best Actress Oscar winner for La Vie en Rose?", "Marion Cotillard", "Marion Cotillard", ["Juliette Binoche", "Isabelle Huppert", "Charlotte Gainsbourg"], ["Juliette Binoche", "Isabelle Huppert", "Charlotte Gainsbourg"]],
  ["Qui a remporté l'Oscar pour La La Land (acteur) ?", "Best Actor Oscar nominee headlining La La Land?", "Ryan Gosling", "Ryan Gosling", ["Casey Affleck", "Denzel Washington", "Andrew Garfield"], ["Casey Affleck", "Denzel Washington", "Andrew Garfield"]],
  ["Qui joue Furiosa dans Mad Max Fury Road ?", "Who plays Furiosa in Mad Max: Fury Road?", "Charlize Theron", "Charlize Theron", ["Cate Blanchett", "Naomi Watts", "Margot Robbie"], ["Cate Blanchett", "Naomi Watts", "Margot Robbie"]],
  ["Qui a remporté l'Oscar pour Whiplash (second rôle) ?", "Best Supporting Actor Oscar for Whiplash?", "J. K. Simmons", "J. K. Simmons", ["Mark Ruffalo", "Edward Norton", "Robert Duvall"], ["Mark Ruffalo", "Edward Norton", "Robert Duvall"]],
  ["Qui joue Cersei Lannister dans Game of Thrones ?", "Who plays Cersei Lannister in Game of Thrones?", "Lena Headey", "Lena Headey", ["Emilia Clarke", "Sophie Turner", "Maisie Williams"], ["Emilia Clarke", "Sophie Turner", "Maisie Williams"]],
  // Musique classique (5)
  ["En quelle année est né Mozart ?", "When was Mozart born?", "1756", "1756", ["1732", "1770", "1791"], ["1732", "1770", "1791"]],
  ["Quelle est la nationalité de Beethoven ?", "What was Beethoven's nationality?", "Allemande", "German", ["Autrichienne", "Italienne", "Polonaise"], ["Austrian", "Italian", "Polish"]],
  ["Qui a composé la Symphonie n°9 (Hymne à la joie) ?", "Who composed Symphony No. 9 (Ode to Joy)?", "Beethoven", "Beethoven", ["Mozart", "Haydn", "Brahms"], ["Mozart", "Haydn", "Brahms"]],
  ["Qui a composé Le Lac des cygnes ?", "Who composed Swan Lake?", "Tchaïkovski", "Tchaikovsky", ["Stravinsky", "Rimsky-Korsakov", "Prokofiev"], ["Stravinsky", "Rimsky-Korsakov", "Prokofiev"]],
  ["Qui a composé l'opéra Carmen ?", "Who composed the opera Carmen?", "Bizet", "Bizet", ["Massenet", "Gounod", "Saint-Saëns"], ["Massenet", "Gounod", "Saint-Saëns"]],
  // Musique rock / pop (5)
  ["Quel album de Pink Floyd est considéré comme un sommet du rock progressif ?", "Which Pink Floyd album is a prog-rock landmark?", "The Dark Side of the Moon", "The Dark Side of the Moon", ["The Wall", "Wish You Were Here", "Animals"], ["The Wall", "Wish You Were Here", "Animals"]],
  ["Quel groupe a chanté Smells Like Teen Spirit ?", "Who sang Smells Like Teen Spirit?", "Nirvana", "Nirvana", ["Pearl Jam", "Soundgarden", "Alice in Chains"], ["Pearl Jam", "Soundgarden", "Alice in Chains"]],
  ["Quel groupe a chanté Hey Jude ?", "Who sang Hey Jude?", "The Beatles", "The Beatles", ["The Rolling Stones", "The Who", "The Kinks"], ["The Rolling Stones", "The Who", "The Kinks"]],
  ["Quel groupe a chanté Stairway to Heaven ?", "Who sang Stairway to Heaven?", "Led Zeppelin", "Led Zeppelin", ["Deep Purple", "Black Sabbath", "Pink Floyd"], ["Deep Purple", "Black Sabbath", "Pink Floyd"]],
  ["Quel groupe a chanté Sweet Child O' Mine ?", "Who sang Sweet Child O' Mine?", "Guns N' Roses", "Guns N' Roses", ["Aerosmith", "Bon Jovi", "Mötley Crüe"], ["Aerosmith", "Bon Jovi", "Mötley Crüe"]],
  // Récompenses cinéma (5)
  ["Quel film a remporté l'Oscar du meilleur film en 2017 ?", "Which film won Best Picture at the 2017 Oscars?", "Moonlight", "Moonlight", ["La La Land", "Manchester by the Sea", "Hidden Figures"], ["La La Land", "Manchester by the Sea", "Hidden Figures"]],
  ["Quel film a remporté l'Oscar du meilleur film en 2019 ?", "Which film won Best Picture at the 2019 Oscars?", "Green Book", "Green Book", ["Roma", "Bohemian Rhapsody", "A Star Is Born"], ["Roma", "Bohemian Rhapsody", "A Star Is Born"]],
  ["Quelle récompense est remise au Festival de Cannes ?", "Which award is given at the Cannes Film Festival?", "Palme d'or", "Palme d'Or", ["Lion d'or", "Ours d'or", "César"], ["Golden Lion", "Golden Bear", "César"]],
  ["Quel film a remporté la Palme d'or 2008 ?", "Which film won the 2008 Palme d'Or?", "Entre les murs", "The Class", ["Gomorra", "Il Divo", "Valse avec Bachir"], ["Gomorrah", "Il Divo", "Waltz with Bashir"]],
  ["Quel film de Bong Joon-ho a remporté l'Oscar du meilleur film ?", "Which Bong Joon-ho film won Best Picture?", "Parasite", "Parasite", ["Memories of Murder", "Snowpiercer", "The Host"], ["Memories of Murder", "Snowpiercer", "The Host"]],
  // Séries (5)
  ["Qui a créé Twin Peaks ?", "Who created Twin Peaks?", "David Lynch", "David Lynch", ["David Cronenberg", "Tim Burton", "M. Night Shyamalan"], ["David Cronenberg", "Tim Burton", "M. Night Shyamalan"]],
  ["Dans quelle ville se déroule The Wire ?", "Where is The Wire set?", "Baltimore", "Baltimore", ["New York", "Chicago", "Los Angeles"], ["New York", "Chicago", "Los Angeles"]],
  ["À quelle décennie se déroule Mad Men ?", "Which decade is Mad Men set in?", "Années 1960", "1960s", ["Années 1950", "Années 1970", "Années 1980"], ["1950s", "1970s", "1980s"]],
  ["Qui joue le rôle principal de Mr Robot ?", "Who plays the lead in Mr. Robot?", "Rami Malek", "Rami Malek", ["Christian Bale", "Jesse Eisenberg", "Andrew Garfield"], ["Christian Bale", "Jesse Eisenberg", "Andrew Garfield"]],
  ["Qui joue Sherlock dans la série BBC Sherlock ?", "Who plays Sherlock in BBC's Sherlock?", "Benedict Cumberbatch", "Benedict Cumberbatch", ["Robert Downey Jr.", "Hugh Laurie", "Henry Cavill"], ["Robert Downey Jr.", "Hugh Laurie", "Henry Cavill"]],
  // Animation / divers (10)
  ["Quel studio a produit Le Voyage de Chihiro ?", "Which studio produced Spirited Away?", "Studio Ghibli", "Studio Ghibli", ["Toei Animation", "Madhouse", "Bones"], ["Toei Animation", "Madhouse", "Bones"]],
  ["Qui a réalisé Princesse Mononoké ?", "Who directed Princess Mononoke?", "Hayao Miyazaki", "Hayao Miyazaki", ["Isao Takahata", "Mamoru Hosoda", "Makoto Shinkai"], ["Isao Takahata", "Mamoru Hosoda", "Makoto Shinkai"]],
  ["Qui a réalisé Akira ?", "Who directed Akira?", "Katsuhiro Ōtomo", "Katsuhiro Ōtomo", ["Hayao Miyazaki", "Mamoru Oshii", "Satoshi Kon"], ["Hayao Miyazaki", "Mamoru Oshii", "Satoshi Kon"]],
  ["Quel pays a produit Squid Game ?", "Which country produced Squid Game?", "Corée du Sud", "South Korea", ["Japon", "Chine", "Vietnam"], ["Japan", "China", "Vietnam"]],
  ["Quelle saga MCU a clôturé la « Saga de l'infini » ?", "Which MCU film closed the Infinity Saga?", "Avengers: Endgame", "Avengers: Endgame", ["Avengers: Infinity War", "Captain Marvel", "Spider-Man: Far From Home"], ["Avengers: Infinity War", "Captain Marvel", "Spider-Man: Far From Home"]],
  ["Qui a écrit Le Seigneur des anneaux ?", "Who wrote The Lord of the Rings?", "J. R. R. Tolkien", "J. R. R. Tolkien", ["C. S. Lewis", "George R. R. Martin", "Terry Pratchett"], ["C. S. Lewis", "George R. R. Martin", "Terry Pratchett"]],
  ["Qui a écrit Le Hobbit ?", "Who wrote The Hobbit?", "J. R. R. Tolkien", "J. R. R. Tolkien", ["C. S. Lewis", "Lewis Carroll", "J. M. Barrie"], ["C. S. Lewis", "Lewis Carroll", "J. M. Barrie"]],
  ["Qui a écrit Crime et Châtiment ?", "Who wrote Crime and Punishment?", "Dostoïevski", "Dostoyevsky", ["Tolstoï", "Tchekhov", "Pouchkine"], ["Tolstoy", "Chekhov", "Pushkin"]],
  ["Qui a chanté Born This Way ?", "Who sang Born This Way?", "Lady Gaga", "Lady Gaga", ["Beyoncé", "Britney Spears", "Christina Aguilera"], ["Beyoncé", "Britney Spears", "Christina Aguilera"]],
  ["Qui chante Shape of You ?", "Who sings Shape of You?", "Ed Sheeran", "Ed Sheeran", ["Justin Bieber", "Bruno Mars", "Sam Smith"], ["Justin Bieber", "Bruno Mars", "Sam Smith"]],
];

/* ── Hard (Platine · 1800 ELO) ────────────────────────────────────── */
const hard: CuratedFact[] = [
  // Réalisateurs auteurs (10)
  ["Qui a réalisé Persona ?", "Who directed Persona?", "Ingmar Bergman", "Ingmar Bergman", ["Lars von Trier", "Carl Dreyer", "Roy Andersson"], ["Lars von Trier", "Carl Dreyer", "Roy Andersson"]],
  ["Qui a réalisé Stalker ?", "Who directed Stalker?", "Andreï Tarkovski", "Andrei Tarkovsky", ["Sergueï Paradjanov", "Aleksandr Sokourov", "Elem Klimov"], ["Sergei Parajanov", "Aleksandr Sokurov", "Elem Klimov"]],
  ["Qui a réalisé Mulholland Drive ?", "Who directed Mulholland Drive?", "David Lynch", "David Lynch", ["David Cronenberg", "Paul Thomas Anderson", "David Fincher"], ["David Cronenberg", "Paul Thomas Anderson", "David Fincher"]],
  ["Qui a réalisé Le Voyage de Chihiro ?", "Who directed Spirited Away?", "Hayao Miyazaki", "Hayao Miyazaki", ["Isao Takahata", "Satoshi Kon", "Makoto Shinkai"], ["Isao Takahata", "Satoshi Kon", "Makoto Shinkai"]],
  ["Qui a réalisé Les Quatre Cents Coups ?", "Who directed The 400 Blows?", "François Truffaut", "François Truffaut", ["Jean-Luc Godard", "Éric Rohmer", "Claude Chabrol"], ["Jean-Luc Godard", "Éric Rohmer", "Claude Chabrol"]],
  ["Qui a réalisé À bout de souffle ?", "Who directed Breathless?", "Jean-Luc Godard", "Jean-Luc Godard", ["François Truffaut", "Alain Resnais", "Agnès Varda"], ["François Truffaut", "Alain Resnais", "Agnès Varda"]],
  ["Qui a réalisé Le Charme discret de la bourgeoisie ?", "Who directed The Discreet Charm of the Bourgeoisie?", "Luis Buñuel", "Luis Buñuel", ["Federico Fellini", "Pedro Almodóvar", "Carlos Saura"], ["Federico Fellini", "Pedro Almodóvar", "Carlos Saura"]],
  ["Qui a réalisé The Tree of Life ?", "Who directed The Tree of Life?", "Terrence Malick", "Terrence Malick", ["Paul Thomas Anderson", "David Fincher", "Christopher Nolan"], ["Paul Thomas Anderson", "David Fincher", "Christopher Nolan"]],
  ["Qui a réalisé In the Mood for Love ?", "Who directed In the Mood for Love?", "Wong Kar-wai", "Wong Kar-wai", ["Ang Lee", "Hou Hsiao-hsien", "Edward Yang"], ["Ang Lee", "Hou Hsiao-hsien", "Edward Yang"]],
  ["Qui a réalisé Memento ?", "Who directed Memento?", "Christopher Nolan", "Christopher Nolan", ["David Fincher", "Darren Aronofsky", "Bryan Singer"], ["David Fincher", "Darren Aronofsky", "Bryan Singer"]],
  // Acteurs spécialisés (10)
  ["Qui joue Daniel Plainview dans There Will Be Blood ?", "Who plays Daniel Plainview in There Will Be Blood?", "Daniel Day-Lewis", "Daniel Day-Lewis", ["Russell Crowe", "Tommy Lee Jones", "Sean Penn"], ["Russell Crowe", "Tommy Lee Jones", "Sean Penn"]],
  ["Qui joue Eli Sunday dans There Will Be Blood ?", "Who plays Eli Sunday in There Will Be Blood?", "Paul Dano", "Paul Dano", ["Casey Affleck", "Joaquin Phoenix", "Andrew Garfield"], ["Casey Affleck", "Joaquin Phoenix", "Andrew Garfield"]],
  ["Quelle actrice française joue dans Trois couleurs : Bleu ?", "Which French actress stars in Three Colors: Blue?", "Juliette Binoche", "Juliette Binoche", ["Isabelle Huppert", "Catherine Deneuve", "Marion Cotillard"], ["Isabelle Huppert", "Catherine Deneuve", "Marion Cotillard"]],
  ["Qui joue l'agent Cooper dans Twin Peaks ?", "Who plays Agent Cooper in Twin Peaks?", "Kyle MacLachlan", "Kyle MacLachlan", ["Mark Frost", "Jeffrey Wright", "Bill Pullman"], ["Mark Frost", "Jeffrey Wright", "Bill Pullman"]],
  ["Quelle actrice gagne l'Oscar pour Boyhood (second rôle) ?", "Best Supporting Actress Oscar for Boyhood?", "Patricia Arquette", "Patricia Arquette", ["Laura Dern", "Emma Stone", "Viola Davis"], ["Laura Dern", "Emma Stone", "Viola Davis"]],
  ["Qui joue Lee Chandler dans Manchester by the Sea ?", "Who plays Lee Chandler in Manchester by the Sea?", "Casey Affleck", "Casey Affleck", ["Ben Affleck", "Mark Ruffalo", "Casey Stoner"], ["Ben Affleck", "Mark Ruffalo", "Joaquin Phoenix"]],
  ["Quelle actrice non professionnelle joue Cleo dans Roma ?", "Who plays Cleo in Roma?", "Yalitza Aparicio", "Yalitza Aparicio", ["Marina de Tavira", "Salma Hayek", "Adriana Barraza"], ["Marina de Tavira", "Salma Hayek", "Adriana Barraza"]],
  ["Quel acteur coréen joue le père dans Parasite ?", "Which Korean actor plays the father in Parasite?", "Song Kang-ho", "Song Kang-ho", ["Lee Sun-kyun", "Choi Woo-shik", "Park Hae-il"], ["Lee Sun-kyun", "Choi Woo-shik", "Park Hae-il"]],
  ["Quel duo joue dans The Lighthouse de 2019 ?", "Which duo stars in 2019's The Lighthouse?", "Pattinson et Dafoe", "Pattinson and Dafoe", ["Pattinson et Phoenix", "Dafoe et Caine", "Pattinson et Bale"], ["Pattinson and Phoenix", "Dafoe and Caine", "Pattinson and Bale"]],
  ["Qui joue Amy Dunne dans Gone Girl ?", "Who plays Amy Dunne in Gone Girl?", "Rosamund Pike", "Rosamund Pike", ["Charlize Theron", "Cate Blanchett", "Reese Witherspoon"], ["Charlize Theron", "Cate Blanchett", "Reese Witherspoon"]],
  // Musique classique (5)
  ["Qui a composé la Symphonie fantastique ?", "Who composed Symphonie fantastique?", "Hector Berlioz", "Hector Berlioz", ["Camille Saint-Saëns", "Gabriel Fauré", "Claude Debussy"], ["Camille Saint-Saëns", "Gabriel Fauré", "Claude Debussy"]],
  ["Qui a composé l'opéra La Traviata ?", "Who composed La Traviata?", "Giuseppe Verdi", "Giuseppe Verdi", ["Giacomo Puccini", "Vincenzo Bellini", "Gaetano Donizetti"], ["Giacomo Puccini", "Vincenzo Bellini", "Gaetano Donizetti"]],
  ["Qui a composé Pelléas et Mélisande ?", "Who composed Pelléas et Mélisande (opera)?", "Claude Debussy", "Claude Debussy", ["Maurice Ravel", "Gabriel Fauré", "Erik Satie"], ["Maurice Ravel", "Gabriel Fauré", "Erik Satie"]],
  ["Qui a composé Le Sacre du printemps ?", "Who composed The Rite of Spring?", "Igor Stravinsky", "Igor Stravinsky", ["Sergueï Prokofiev", "Dmitri Chostakovitch", "Béla Bartók"], ["Sergei Prokofiev", "Dmitri Shostakovich", "Béla Bartók"]],
  ["Qui a composé Valse triste ?", "Who composed Valse triste?", "Jean Sibelius", "Jean Sibelius", ["Edvard Grieg", "Carl Nielsen", "Wilhelm Stenhammar"], ["Edvard Grieg", "Carl Nielsen", "Wilhelm Stenhammar"]],
  // Musique rock (5)
  ["Quel groupe a sorti l'album London Calling ?", "Who released the album London Calling?", "The Clash", "The Clash", ["Sex Pistols", "Ramones", "Buzzcocks"], ["Sex Pistols", "Ramones", "Buzzcocks"]],
  ["Quel groupe a sorti Pet Sounds ?", "Who released Pet Sounds?", "The Beach Boys", "The Beach Boys", ["The Beatles", "The Byrds", "The Mamas and the Papas"], ["The Beatles", "The Byrds", "The Mamas and the Papas"]],
  ["Quel album des Beatles s'ouvre sur Sgt. Pepper's Lonely Hearts Club Band ?", "Which Beatles album opens with Sgt. Pepper's Lonely Hearts Club Band?", "Sgt. Pepper's Lonely Hearts Club Band", "Sgt. Pepper's Lonely Hearts Club Band", ["Abbey Road", "Revolver", "The White Album"], ["Abbey Road", "Revolver", "The White Album"]],
  ["Quel album de U2 inclut Where the Streets Have No Name ?", "Which U2 album includes Where the Streets Have No Name?", "The Joshua Tree", "The Joshua Tree", ["Achtung Baby", "Boy", "War"], ["Achtung Baby", "Boy", "War"]],
  ["Quel album de Pink Floyd raconte l'isolement et le mur intérieur ?", "Which Pink Floyd album tells the story of an isolated wall?", "The Wall", "The Wall", ["The Dark Side of the Moon", "Animals", "Wish You Were Here"], ["The Dark Side of the Moon", "Animals", "Wish You Were Here"]],
  // Séries spécifiques (5)
  ["Qui a créé Six Feet Under ?", "Who created Six Feet Under?", "Alan Ball", "Alan Ball", ["David Chase", "Vince Gilligan", "Aaron Sorkin"], ["David Chase", "Vince Gilligan", "Aaron Sorkin"]],
  ["Qui a créé Black Mirror ?", "Who created Black Mirror?", "Charlie Brooker", "Charlie Brooker", ["Russell T Davies", "Steven Moffat", "Mark Gatiss"], ["Russell T Davies", "Steven Moffat", "Mark Gatiss"]],
  ["Better Call Saul est un préquel de quelle série ?", "Better Call Saul is a prequel to which series?", "Breaking Bad", "Breaking Bad", ["The Wire", "Justified", "Fargo"], ["The Wire", "Justified", "Fargo"]],
  ["Westworld (HBO) est inspirée d'un film de quelle année ?", "Westworld (HBO) is based on a film from which year?", "1973", "1973", ["1968", "1985", "1990"], ["1968", "1985", "1990"]],
  ["Qui a créé The Crown ?", "Who created The Crown?", "Peter Morgan", "Peter Morgan", ["Julian Fellowes", "Andrew Davies", "Stephen Daldry"], ["Julian Fellowes", "Andrew Davies", "Stephen Daldry"]],
  // Littérature (5)
  ["Qui a écrit À la recherche du temps perdu ?", "Who wrote In Search of Lost Time?", "Marcel Proust", "Marcel Proust", ["André Gide", "Albert Camus", "Jean-Paul Sartre"], ["André Gide", "Albert Camus", "Jean-Paul Sartre"]],
  ["Qui a écrit Cent ans de solitude ?", "Who wrote One Hundred Years of Solitude?", "Gabriel García Márquez", "Gabriel García Márquez", ["Mario Vargas Llosa", "Carlos Fuentes", "Julio Cortázar"], ["Mario Vargas Llosa", "Carlos Fuentes", "Julio Cortázar"]],
  ["Qui a écrit Anna Karénine ?", "Who wrote Anna Karenina?", "Léon Tolstoï", "Leo Tolstoy", ["Fiodor Dostoïevski", "Anton Tchekhov", "Alexandre Pouchkine"], ["Fyodor Dostoyevsky", "Anton Chekhov", "Alexander Pushkin"]],
  ["Qui a écrit La Métamorphose ?", "Who wrote The Metamorphosis?", "Franz Kafka", "Franz Kafka", ["Thomas Mann", "Hermann Hesse", "Robert Musil"], ["Thomas Mann", "Hermann Hesse", "Robert Musil"]],
  ["Qui a écrit Le Maître et Marguerite ?", "Who wrote The Master and Margarita?", "Mikhaïl Boulgakov", "Mikhail Bulgakov", ["Andreï Biély", "Boris Pasternak", "Vladimir Nabokov"], ["Andrei Bely", "Boris Pasternak", "Vladimir Nabokov"]],
  // Récompenses (5)
  ["Quel film de Bong Joon-ho a reçu la Palme d'or 2019 ?", "Which Bong Joon-ho film won the 2019 Palme d'Or?", "Parasite", "Parasite", ["Snowpiercer", "Memories of Murder", "Okja"], ["Snowpiercer", "Memories of Murder", "Okja"]],
  ["Quel festival décerne le Lion d'or ?", "Which festival awards the Golden Lion?", "Mostra de Venise", "Venice Film Festival", ["Berlinale", "Cannes", "Sundance"], ["Berlinale", "Cannes", "Sundance"]],
  ["Quel festival décerne l'Ours d'or ?", "Which festival awards the Golden Bear?", "Berlinale", "Berlinale", ["Cannes", "Mostra", "Toronto"], ["Cannes", "Venice", "Toronto"]],
  ["Quel acteur a remporté 3 Oscars du meilleur acteur ?", "Which actor has won 3 Best Actor Oscars?", "Daniel Day-Lewis", "Daniel Day-Lewis", ["Jack Nicholson", "Marlon Brando", "Robert De Niro"], ["Jack Nicholson", "Marlon Brando", "Robert De Niro"]],
  ["Quel film de Bong Joon-ho a remporté 4 Oscars dont meilleur réalisateur ?", "Which Bong Joon-ho film won 4 Oscars including Best Director?", "Parasite", "Parasite", ["Snowpiercer", "The Host", "Okja"], ["Snowpiercer", "The Host", "Okja"]],
  // Compléments hard (5)
  ["Qui a réalisé la trilogie Three Colors (Bleu, Blanc, Rouge) ?", "Who directed the Three Colors trilogy?", "Krzysztof Kieślowski", "Krzysztof Kieślowski", ["Andrzej Wajda", "Roman Polanski", "Agnieszka Holland"], ["Andrzej Wajda", "Roman Polanski", "Agnieszka Holland"]],
  ["Qui joue le Capitaine Willard dans Apocalypse Now ?", "Who plays Captain Willard in Apocalypse Now?", "Martin Sheen", "Martin Sheen", ["Robert Duvall", "Marlon Brando", "Dennis Hopper"], ["Robert Duvall", "Marlon Brando", "Dennis Hopper"]],
  ["Quel album de Radiohead inclut Paranoid Android ?", "Which Radiohead album includes Paranoid Android?", "OK Computer", "OK Computer", ["Kid A", "The Bends", "In Rainbows"], ["Kid A", "The Bends", "In Rainbows"]],
  ["Qui a écrit le roman Cent ans de solitude (lauréat Nobel) ?", "Who wrote One Hundred Years of Solitude (Nobel laureate)?", "Gabriel García Márquez", "Gabriel García Márquez", ["Pablo Neruda", "Mario Vargas Llosa", "Octavio Paz"], ["Pablo Neruda", "Mario Vargas Llosa", "Octavio Paz"]],
  ["Quel chef d'orchestre a dirigé la Philharmonique de Berlin de 1955 à 1989 ?", "Who led the Berlin Philharmonic from 1955 to 1989?", "Herbert von Karajan", "Herbert von Karajan", ["Wilhelm Furtwängler", "Claudio Abbado", "Simon Rattle"], ["Wilhelm Furtwängler", "Claudio Abbado", "Simon Rattle"]],
];

/* ── Expert (Diamant · 2200 ELO) ──────────────────────────────────── */
const expert: CuratedFact[] = [
  // Réalisateurs très pointus (10)
  ["Qui a réalisé L'Année dernière à Marienbad ?", "Who directed Last Year at Marienbad?", "Alain Resnais", "Alain Resnais", ["Chris Marker", "Jean-Pierre Melville", "Robert Bresson"], ["Chris Marker", "Jean-Pierre Melville", "Robert Bresson"]],
  ["Qui a réalisé Sátántangó ?", "Who directed Sátántangó?", "Béla Tarr", "Béla Tarr", ["Miklós Jancsó", "István Szabó", "Krzysztof Kieślowski"], ["Miklós Jancsó", "István Szabó", "Krzysztof Kieślowski"]],
  ["Qui a réalisé Cléo de 5 à 7 ?", "Who directed Cléo from 5 to 7?", "Agnès Varda", "Agnès Varda", ["Jacques Demy", "Chantal Akerman", "Marguerite Duras"], ["Jacques Demy", "Chantal Akerman", "Marguerite Duras"]],
  ["Qui a réalisé Andreï Roublev ?", "Who directed Andrei Rublev?", "Andreï Tarkovski", "Andrei Tarkovsky", ["Sergueï Eisenstein", "Mikhaïl Romm", "Aleksandr Sokourov"], ["Sergei Eisenstein", "Mikhail Romm", "Aleksandr Sokurov"]],
  ["Qui a réalisé Le Cuirassé Potemkine ?", "Who directed Battleship Potemkin?", "Sergueï Eisenstein", "Sergei Eisenstein", ["Vsevolod Poudovkine", "Dziga Vertov", "Aleksandr Dovjenko"], ["Vsevolod Pudovkin", "Dziga Vertov", "Aleksandr Dovzhenko"]],
  ["Qui a réalisé Le Goût de la cerise (Palme d'or 1997) ?", "Who directed Taste of Cherry (1997 Palme d'Or)?", "Abbas Kiarostami", "Abbas Kiarostami", ["Mohsen Makhmalbaf", "Jafar Panahi", "Asghar Farhadi"], ["Mohsen Makhmalbaf", "Jafar Panahi", "Asghar Farhadi"]],
  ["Qui a réalisé Tokyo Story ?", "Who directed Tokyo Story?", "Yasujirō Ozu", "Yasujirō Ozu", ["Kenji Mizoguchi", "Akira Kurosawa", "Mikio Naruse"], ["Kenji Mizoguchi", "Akira Kurosawa", "Mikio Naruse"]],
  ["Qui a réalisé Le Guépard ?", "Who directed The Leopard?", "Luchino Visconti", "Luchino Visconti", ["Federico Fellini", "Bernardo Bertolucci", "Vittorio De Sica"], ["Federico Fellini", "Bernardo Bertolucci", "Vittorio De Sica"]],
  ["Qui a réalisé Salò ou les 120 journées de Sodome ?", "Who directed Salò, or the 120 Days of Sodom?", "Pier Paolo Pasolini", "Pier Paolo Pasolini", ["Bernardo Bertolucci", "Marco Ferreri", "Liliana Cavani"], ["Bernardo Bertolucci", "Marco Ferreri", "Liliana Cavani"]],
  ["Qui a réalisé Underground (Palme d'or 1995) ?", "Who directed Underground (1995 Palme d'Or)?", "Emir Kusturica", "Emir Kusturica", ["Theo Angelopoulos", "Mihalkov", "Aleksandar Petrović"], ["Theo Angelopoulos", "Mikhalkov", "Aleksandar Petrović"]],
  // Acteurs / réalisateurs experts (10)
  ["Quel acteur joue dans presque tous les films de Wes Anderson ?", "Which actor recurs in most Wes Anderson films?", "Bill Murray", "Bill Murray", ["Edward Norton", "Owen Wilson", "Jason Schwartzman"], ["Edward Norton", "Owen Wilson", "Jason Schwartzman"]],
  ["Quelle actrice joue Karin dans Cris et Chuchotements de Bergman ?", "Who plays Karin in Bergman's Cries and Whispers?", "Ingrid Thulin", "Ingrid Thulin", ["Liv Ullmann", "Bibi Andersson", "Harriet Andersson"], ["Liv Ullmann", "Bibi Andersson", "Harriet Andersson"]],
  ["Qui joue Travis Bickle dans Taxi Driver ?", "Who plays Travis Bickle in Taxi Driver?", "Robert De Niro", "Robert De Niro", ["Al Pacino", "Harvey Keitel", "Dustin Hoffman"], ["Al Pacino", "Harvey Keitel", "Dustin Hoffman"]],
  ["Qui a réalisé Stalker, Solaris et Le Sacrifice ?", "Who directed Stalker, Solaris and The Sacrifice?", "Andreï Tarkovski", "Andrei Tarkovsky", ["Aleksandr Sokourov", "Sergueï Paradjanov", "Elem Klimov"], ["Aleksandr Sokurov", "Sergei Parajanov", "Elem Klimov"]],
  ["Qui a réalisé Les Contes de la lune vague après la pluie ?", "Who directed Ugetsu Monogatari?", "Kenji Mizoguchi", "Kenji Mizoguchi", ["Yasujirō Ozu", "Mikio Naruse", "Akira Kurosawa"], ["Yasujirō Ozu", "Mikio Naruse", "Akira Kurosawa"]],
  ["Qui a réalisé La Maman et la Putain ?", "Who directed The Mother and the Whore?", "Jean Eustache", "Jean Eustache", ["Maurice Pialat", "Philippe Garrel", "Robert Bresson"], ["Maurice Pialat", "Philippe Garrel", "Robert Bresson"]],
  ["Qui a réalisé Ma nuit chez Maud ?", "Who directed My Night at Maud's?", "Éric Rohmer", "Éric Rohmer", ["François Truffaut", "Claude Chabrol", "Jacques Rivette"], ["François Truffaut", "Claude Chabrol", "Jacques Rivette"]],
  ["Qui a réalisé Oncle Boonmee, Palme d'or 2010 ?", "Who directed Uncle Boonmee (2010 Palme d'Or)?", "Apichatpong Weerasethakul", "Apichatpong Weerasethakul", ["Pen-ek Ratanaruang", "Hou Hsiao-hsien", "Tsai Ming-liang"], ["Pen-ek Ratanaruang", "Hou Hsiao-hsien", "Tsai Ming-liang"]],
  ["Qui a écrit et réalisé Holy Motors ?", "Who wrote and directed Holy Motors?", "Leos Carax", "Leos Carax", ["Bruno Dumont", "Olivier Assayas", "Arnaud Desplechin"], ["Bruno Dumont", "Olivier Assayas", "Arnaud Desplechin"]],
  ["Qui a réalisé Lawrence d'Arabie ?", "Who directed Lawrence of Arabia?", "David Lean", "David Lean", ["John Ford", "William Wyler", "Anthony Mann"], ["John Ford", "William Wyler", "Anthony Mann"]],
  // Musique classique pointue (5)
  ["Qui a composé Le Clavier bien tempéré ?", "Who composed The Well-Tempered Clavier?", "Jean-Sébastien Bach", "Johann Sebastian Bach", ["Georg Friedrich Haendel", "Domenico Scarlatti", "Antonio Vivaldi"], ["George Frideric Handel", "Domenico Scarlatti", "Antonio Vivaldi"]],
  ["Qui a composé Götterdämmerung ?", "Who composed Götterdämmerung?", "Richard Wagner", "Richard Wagner", ["Richard Strauss", "Gustav Mahler", "Anton Bruckner"], ["Richard Strauss", "Gustav Mahler", "Anton Bruckner"]],
  ["Qui a composé le Boléro ?", "Who composed Boléro?", "Maurice Ravel", "Maurice Ravel", ["Claude Debussy", "Erik Satie", "Gabriel Fauré"], ["Claude Debussy", "Erik Satie", "Gabriel Fauré"]],
  ["Qui a composé la Polonaise héroïque ?", "Who composed the Heroic Polonaise?", "Frédéric Chopin", "Frédéric Chopin", ["Franz Liszt", "Robert Schumann", "Felix Mendelssohn"], ["Franz Liszt", "Robert Schumann", "Felix Mendelssohn"]],
  ["Qui a composé Le Château de Barbe-Bleue ?", "Who composed Bluebeard's Castle?", "Béla Bartók", "Béla Bartók", ["Zoltán Kodály", "Ernő Dohnányi", "György Ligeti"], ["Zoltán Kodály", "Ernő Dohnányi", "György Ligeti"]],
  // Jazz / experimental (5)
  ["Quel album de Miles Davis a inventé le jazz modal ?", "Which Miles Davis album invented modal jazz?", "Kind of Blue", "Kind of Blue", ["Bitches Brew", "In a Silent Way", "Sketches of Spain"], ["Bitches Brew", "In a Silent Way", "Sketches of Spain"]],
  ["Quel saxophoniste a sorti A Love Supreme ?", "Which saxophonist released A Love Supreme?", "John Coltrane", "John Coltrane", ["Sonny Rollins", "Wayne Shorter", "Charlie Parker"], ["Sonny Rollins", "Wayne Shorter", "Charlie Parker"]],
  ["Qui a improvisé The Köln Concert ?", "Who improvised The Köln Concert?", "Keith Jarrett", "Keith Jarrett", ["Brad Mehldau", "Chick Corea", "Bill Evans"], ["Brad Mehldau", "Chick Corea", "Bill Evans"]],
  ["Qui a sorti Take Five ?", "Who released Take Five?", "Dave Brubeck", "Dave Brubeck", ["Stan Getz", "Paul Desmond", "Gerry Mulligan"], ["Stan Getz", "Paul Desmond", "Gerry Mulligan"]],
  ["Quel album marque le tournant fusion de Miles Davis ?", "Which album marked Miles Davis' fusion turn?", "Bitches Brew", "Bitches Brew", ["Kind of Blue", "On the Corner", "Tutu"], ["Kind of Blue", "On the Corner", "Tutu"]],
  // Littérature très pointue (5)
  ["Qui a écrit Ulysse ?", "Who wrote Ulysses?", "James Joyce", "James Joyce", ["Samuel Beckett", "Virginia Woolf", "T. S. Eliot"], ["Samuel Beckett", "Virginia Woolf", "T. S. Eliot"]],
  ["Qui a écrit Sous le volcan ?", "Who wrote Under the Volcano?", "Malcolm Lowry", "Malcolm Lowry", ["Graham Greene", "Evelyn Waugh", "D. H. Lawrence"], ["Graham Greene", "Evelyn Waugh", "D. H. Lawrence"]],
  ["Qui a écrit L'Homme sans qualités ?", "Who wrote The Man Without Qualities?", "Robert Musil", "Robert Musil", ["Hermann Broch", "Joseph Roth", "Stefan Zweig"], ["Hermann Broch", "Joseph Roth", "Stefan Zweig"]],
  ["Qui a écrit Voyage au bout de la nuit ?", "Who wrote Journey to the End of the Night?", "Louis-Ferdinand Céline", "Louis-Ferdinand Céline", ["Jean Genet", "Antonin Artaud", "Pierre Drieu la Rochelle"], ["Jean Genet", "Antonin Artaud", "Pierre Drieu la Rochelle"]],
  ["Qui a écrit Gravity's Rainbow ?", "Who wrote Gravity's Rainbow?", "Thomas Pynchon", "Thomas Pynchon", ["Don DeLillo", "Cormac McCarthy", "John Barth"], ["Don DeLillo", "Cormac McCarthy", "John Barth"]],
  // Animation / studio (5)
  ["En quelle année a été fondé le Studio Ghibli ?", "When was Studio Ghibli founded?", "1985", "1985", ["1979", "1991", "1973"], ["1979", "1991", "1973"]],
  ["Quel premier long-métrage Disney en couleurs sortit en 1937 ?", "First feature-length Disney color film (1937)?", "Blanche-Neige et les Sept Nains", "Snow White and the Seven Dwarfs", ["Pinocchio", "Bambi", "Fantasia"], ["Pinocchio", "Bambi", "Fantasia"]],
  ["En quelle année Disney a-t-il racheté Pixar ?", "When did Disney acquire Pixar?", "2006", "2006", ["1996", "2009", "2012"], ["1996", "2009", "2012"]],
  ["Qui a fondé Pixar avec John Lasseter ?", "Who co-founded Pixar with John Lasseter?", "Edwin Catmull et Steve Jobs", "Ed Catmull and Steve Jobs", ["Steve Jobs et Walt Disney", "Brad Bird et Pete Docter", "Andrew Stanton et George Lucas"], ["Steve Jobs and Walt Disney", "Brad Bird and Pete Docter", "Andrew Stanton and George Lucas"]],
  ["Quel premier court-métrage Disney en couleurs (Silly Symphonies) ?", "First Disney color short (Silly Symphonies)?", "Flowers and Trees", "Flowers and Trees", ["Steamboat Willie", "The Skeleton Dance", "Three Little Pigs"], ["Steamboat Willie", "The Skeleton Dance", "Three Little Pigs"]],
  // Théâtre / opéra / divers (10)
  ["Dans quelle ville se tient le festival d'opéra dédié à Wagner ?", "Which city hosts the Wagner opera festival?", "Bayreuth", "Bayreuth", ["Salzbourg", "Munich", "Vienne"], ["Salzburg", "Munich", "Vienna"]],
  ["En quelle année fut fondée la Comédie-Française ?", "When was the Comédie-Française founded?", "1680", "1680", ["1635", "1715", "1789"], ["1635", "1715", "1789"]],
  ["Dans quel théâtre londonien Shakespeare a-t-il créé ses pièces ?", "In which London theatre did Shakespeare premiere his plays?", "Le Théâtre du Globe", "The Globe Theatre", ["Drury Lane", "Théâtre Royal", "Old Vic"], ["Drury Lane", "Theatre Royal", "Old Vic"]],
  ["Quelle première Palme d'or fut remise à Marty en 1955 ?", "Which film won the first Palme d'Or in 1955?", "Marty", "Marty", ["La Dolce Vita", "Le Salaire de la peur", "Orfeu Negro"], ["La Dolce Vita", "The Wages of Fear", "Black Orpheus"]],
  ["Quel premier Oscar du meilleur film fut remis à Wings en 1929 ?", "Which film won the first Best Picture Oscar (1929)?", "Wings", "Wings", ["Sunrise", "Casablanca", "All Quiet on the Western Front"], ["Sunrise", "Casablanca", "All Quiet on the Western Front"]],
  ["Quel film fut le premier à gagner Palme d'or ET Oscar du meilleur film ?", "First film to win both Palme d'Or and Best Picture Oscar?", "Marty", "Marty", ["Parasite", "The Lost Weekend", "Le Pianiste"], ["Parasite", "The Lost Weekend", "The Pianist"]],
  ["Qui a réalisé le manga et l'anime Berserk ?", "Who created the manga Berserk?", "Kentarō Miura", "Kentarō Miura", ["Naoki Urasawa", "Hirohiko Araki", "Hayao Miyazaki"], ["Naoki Urasawa", "Hirohiko Araki", "Hayao Miyazaki"]],
  ["Qui a réalisé Perfect Blue (anime de 1997) ?", "Who directed Perfect Blue (1997 anime)?", "Satoshi Kon", "Satoshi Kon", ["Mamoru Oshii", "Hideaki Anno", "Mamoru Hosoda"], ["Mamoru Oshii", "Hideaki Anno", "Mamoru Hosoda"]],
  ["Qui a écrit le scénario de Charlie Kaufman pour Synecdoche New York ?", "Who wrote and directed Synecdoche, New York?", "Charlie Kaufman", "Charlie Kaufman", ["Spike Jonze", "Wes Anderson", "Paul Thomas Anderson"], ["Spike Jonze", "Wes Anderson", "Paul Thomas Anderson"]],
  ["Quel groupe a sorti l'album OK Computer en 1997 ?", "Who released OK Computer in 1997?", "Radiohead", "Radiohead", ["Blur", "Oasis", "Pulp"], ["Blur", "Oasis", "Pulp"]],
];

export const ENTERTAINMENT_QUESTIONS = buildCuratedCategory(
  "entertainment",
  "ent",
  [easy, medium, hard, expert],
);
