import { buildCuratedCategory, type CuratedFact } from "./_builder";

/* ── Easy (Argent · 1000 ELO) ─────────────────────────────────────── */
const easy: CuratedFact[] = [
  // Chimie / éléments (10)
  ["Quel est le symbole chimique de l'or ?", "Chemical symbol for gold?", "Au", "Au", ["Ag", "Or", "Hg"], ["Ag", "Or", "Hg"]],
  ["Quel est le symbole chimique de l'argent ?", "Chemical symbol for silver?", "Ag", "Ag", ["Au", "Si", "S"], ["Au", "Si", "S"]],
  ["Quel est le symbole chimique du fer ?", "Chemical symbol for iron?", "Fe", "Fe", ["Ir", "Fr", "F"], ["Ir", "Fr", "F"]],
  ["Quel est le symbole chimique du cuivre ?", "Chemical symbol for copper?", "Cu", "Cu", ["Co", "Cr", "C"], ["Co", "Cr", "C"]],
  ["Quel est le symbole chimique du sodium ?", "Chemical symbol for sodium?", "Na", "Na", ["So", "S", "N"], ["So", "S", "N"]],
  ["Quelle est la formule chimique de l'eau ?", "Chemical formula for water?", "H2O", "H2O", ["CO2", "O2", "NaCl"], ["CO2", "O2", "NaCl"]],
  ["Quelle est la formule du dioxyde de carbone ?", "Chemical formula for carbon dioxide?", "CO2", "CO2", ["CO", "C2O", "O2"], ["CO", "C2O", "O2"]],
  ["Quelle est la formule du sel de table ?", "Chemical formula for table salt?", "NaCl", "NaCl", ["KCl", "CaCl2", "NaOH"], ["KCl", "CaCl2", "NaOH"]],
  ["Quel est l'élément le plus abondant dans l'univers ?", "Most abundant element in the universe?", "Hydrogène", "Hydrogen", ["Hélium", "Oxygène", "Carbone"], ["Helium", "Oxygen", "Carbon"]],
  ["Quel gaz est principalement présent dans l'air ?", "Which gas dominates Earth's atmosphere?", "Diazote (N2)", "Nitrogen (N2)", ["Dioxygène (O2)", "Dioxyde de carbone", "Argon"], ["Oxygen (O2)", "Carbon dioxide", "Argon"]],
  // Astronomie (10)
  ["Quelle est la planète la plus proche du Soleil ?", "Closest planet to the Sun?", "Mercure", "Mercury", ["Vénus", "Mars", "Terre"], ["Venus", "Mars", "Earth"]],
  ["Quelle est la plus grande planète du système solaire ?", "Largest planet in the solar system?", "Jupiter", "Jupiter", ["Saturne", "Neptune", "Uranus"], ["Saturn", "Neptune", "Uranus"]],
  ["Quelle planète est appelée la planète rouge ?", "Which planet is called the red planet?", "Mars", "Mars", ["Mercure", "Jupiter", "Vénus"], ["Mercury", "Jupiter", "Venus"]],
  ["Quelle planète est connue pour ses anneaux ?", "Which planet is famous for its rings?", "Saturne", "Saturn", ["Jupiter", "Uranus", "Neptune"], ["Jupiter", "Uranus", "Neptune"]],
  ["Combien y a-t-il de planètes dans le système solaire ?", "How many planets in the solar system?", "8", "8", ["7", "9", "10"], ["7", "9", "10"]],
  ["Comment s'appelle la galaxie qui contient la Terre ?", "Name of the galaxy containing Earth?", "Voie lactée", "Milky Way", ["Andromède", "Triangle", "Sombrero"], ["Andromeda", "Triangulum", "Sombrero"]],
  ["Quel est le satellite naturel de la Terre ?", "What is Earth's natural satellite?", "La Lune", "The Moon", ["Phobos", "Deimos", "Charon"], ["Phobos", "Deimos", "Charon"]],
  ["Qui fut le premier humain à marcher sur la Lune ?", "Who was the first human on the Moon?", "Neil Armstrong", "Neil Armstrong", ["Buzz Aldrin", "Yuri Gagarine", "Michael Collins"], ["Buzz Aldrin", "Yuri Gagarin", "Michael Collins"]],
  ["Combien de temps met la Terre à orbiter le Soleil ?", "How long does Earth take to orbit the Sun?", "1 an", "1 year", ["6 mois", "2 ans", "1 mois"], ["6 months", "2 years", "1 month"]],
  ["Quelle est l'étoile la plus proche de la Terre ?", "Closest star to Earth?", "Le Soleil", "The Sun", ["Proxima du Centaure", "Sirius", "Bételgeuse"], ["Proxima Centauri", "Sirius", "Betelgeuse"]],
  // Biologie / corps (10)
  ["Quel organe pompe le sang dans le corps ?", "Which organ pumps blood?", "Cœur", "Heart", ["Poumons", "Foie", "Reins"], ["Lungs", "Liver", "Kidneys"]],
  ["Combien d'os a un corps humain adulte ?", "How many bones in an adult human body?", "206", "206", ["180", "230", "300"], ["180", "230", "300"]],
  ["Combien de chambres a le cœur humain ?", "How many chambers in a human heart?", "4", "4", ["2", "3", "5"], ["2", "3", "5"]],
  ["Combien de chromosomes a un humain ?", "How many chromosomes do humans have?", "46", "46", ["23", "44", "48"], ["23", "44", "48"]],
  ["Quel est le plus grand organe du corps humain ?", "Largest organ in the human body?", "Peau", "Skin", ["Foie", "Cerveau", "Intestin"], ["Liver", "Brain", "Intestine"]],
  ["Quel est l'animal terrestre le plus rapide ?", "Fastest land animal?", "Guépard", "Cheetah", ["Lion", "Antilope", "Cheval"], ["Lion", "Antelope", "Horse"]],
  ["Quel est le plus grand mammifère du monde ?", "Largest mammal in the world?", "Baleine bleue", "Blue whale", ["Éléphant d'Afrique", "Cachalot", "Baleine grise"], ["African elephant", "Sperm whale", "Gray whale"]],
  ["Quel mammifère pond des œufs ?", "Which mammal lays eggs?", "Ornithorynque", "Platypus", ["Échidné australien", "Hérisson", "Tatou"], ["Australian echidna", "Hedgehog", "Armadillo"]],
  ["Combien de dents a un adulte ?", "How many teeth does an adult human have?", "32", "32", ["20", "28", "36"], ["20", "28", "36"]],
  ["Combien de pattes a une araignée ?", "How many legs does a spider have?", "8", "8", ["6", "10", "12"], ["6", "10", "12"]],
  // Physique (5)
  ["Quelle est la vitesse de la lumière (km/s) ?", "Speed of light (km/s)?", "300 000", "300,000", ["150 000", "1 000 000", "30 000"], ["150,000", "1,000,000", "30,000"]],
  ["Quelle est la valeur de g à la surface terrestre (m/s²) ?", "Surface gravity g (m/s²)?", "9.81", "9.81", ["8.31", "10.5", "7.5"], ["8.31", "10.5", "7.5"]],
  ["En quelle unité mesure-t-on une force ?", "Unit for measuring force?", "Newton", "Newton", ["Joule", "Pascal", "Watt"], ["Joule", "Pascal", "Watt"]],
  ["En quelle unité mesure-t-on une énergie ?", "Unit for measuring energy?", "Joule", "Joule", ["Newton", "Watt", "Volt"], ["Newton", "Watt", "Volt"]],
  ["Quelle est la température du zéro absolu ?", "Temperature of absolute zero?", "-273.15 °C", "-273.15 °C", ["0 °C", "-100 °C", "-459.67 °F (autre formulation)"], ["0 °C", "-100 °C", "-459.67 °F (other unit)"]],
  // Mathématiques (5)
  ["Quelle est la valeur approximative de pi ?", "Approximate value of π?", "3.14", "3.14", ["2.72", "1.41", "1.62"], ["2.72", "1.41", "1.62"]],
  ["Combien de degrés dans un cercle ?", "Degrees in a circle?", "360", "360", ["180", "90", "720"], ["180", "90", "720"]],
  ["Quelle est la racine carrée de 144 ?", "Square root of 144?", "12", "12", ["10", "14", "16"], ["10", "14", "16"]],
  ["Combien font 12 × 12 ?", "What is 12 × 12?", "144", "144", ["132", "156", "121"], ["132", "156", "121"]],
  ["Combien de minutes dans une heure ?", "Minutes in an hour?", "60", "60", ["30", "100", "120"], ["30", "100", "120"]],
  // Inventeurs / découvertes (5)
  ["Qui a découvert la loi de la gravitation universelle ?", "Who formulated universal gravitation?", "Isaac Newton", "Isaac Newton", ["Albert Einstein", "Galilée", "Stephen Hawking"], ["Albert Einstein", "Galileo", "Stephen Hawking"]],
  ["Qui a formulé la théorie de la relativité ?", "Who formulated relativity?", "Albert Einstein", "Albert Einstein", ["Isaac Newton", "Niels Bohr", "Stephen Hawking"], ["Isaac Newton", "Niels Bohr", "Stephen Hawking"]],
  ["Qui a découvert la pénicilline ?", "Who discovered penicillin?", "Alexander Fleming", "Alexander Fleming", ["Louis Pasteur", "Robert Koch", "Marie Curie"], ["Louis Pasteur", "Robert Koch", "Marie Curie"]],
  ["Qui a formulé la théorie de l'évolution par sélection naturelle ?", "Who formulated evolution by natural selection?", "Charles Darwin", "Charles Darwin", ["Lamarck", "Mendel", "Wallace seul"], ["Lamarck", "Mendel", "Wallace alone"]],
  ["Qui a établi le tableau périodique des éléments ?", "Who built the periodic table?", "Mendeleïev", "Mendeleev", ["Avogadro", "Lavoisier", "Bohr"], ["Avogadro", "Lavoisier", "Bohr"]],
  // Misc (5)
  ["Combien de pattes a un insecte typique ?", "How many legs does a typical insect have?", "6", "6", ["4", "8", "10"], ["4", "8", "10"]],
  ["Combien y a-t-il de continents ?", "How many continents are there?", "7", "7", ["5", "6", "8"], ["5", "6", "8"]],
  ["Quel est le plus grand mammifère terrestre ?", "Largest land mammal?", "Éléphant d'Afrique", "African elephant", ["Hippopotame", "Rhinocéros", "Girafe"], ["Hippopotamus", "Rhinoceros", "Giraffe"]],
  ["Quel oiseau est le plus rapide en piqué ?", "Fastest bird in a dive?", "Faucon pèlerin", "Peregrine falcon", ["Aigle royal", "Albatros", "Condor des Andes"], ["Golden eagle", "Albatross", "Andean condor"]],
  ["Quel mammifère est le seul à voler véritablement ?", "Only mammal that truly flies?", "Chauve-souris", "Bat", ["Écureuil volant", "Pétaure", "Galéopithèque"], ["Flying squirrel", "Sugar glider", "Colugo"]],
];

/* ── Medium (Or · 1400 ELO) ───────────────────────────────────────── */
const medium: CuratedFact[] = [
  // Chimie (10)
  ["Quel élément a pour symbole H ?", "Which element has symbol H?", "Hydrogène", "Hydrogen", ["Hélium", "Hafnium", "Holmium"], ["Helium", "Hafnium", "Holmium"]],
  ["Quel élément a pour symbole He ?", "Which element has symbol He?", "Hélium", "Helium", ["Hydrogène", "Hafnium", "Mercure"], ["Hydrogen", "Hafnium", "Mercury"]],
  ["Quel élément a pour symbole C ?", "Which element has symbol C?", "Carbone", "Carbon", ["Calcium", "Chlore", "Cobalt"], ["Calcium", "Chlorine", "Cobalt"]],
  ["Quel élément a pour symbole O ?", "Which element has symbol O?", "Oxygène", "Oxygen", ["Or", "Osmium", "Argon"], ["Gold", "Osmium", "Argon"]],
  ["Quel élément a pour symbole K ?", "Which element has symbol K?", "Potassium", "Potassium", ["Krypton", "Calcium", "Sodium"], ["Krypton", "Calcium", "Sodium"]],
  ["Quel élément a pour symbole N ?", "Which element has symbol N?", "Azote", "Nitrogen", ["Néon", "Sodium", "Nickel"], ["Neon", "Sodium", "Nickel"]],
  ["Quel élément a pour symbole Mg ?", "Which element has symbol Mg?", "Magnésium", "Magnesium", ["Manganèse", "Mercure", "Molybdène"], ["Manganese", "Mercury", "Molybdenum"]],
  ["Quel élément a pour symbole Ca ?", "Which element has symbol Ca?", "Calcium", "Calcium", ["Carbone", "Chlore", "Cadmium"], ["Carbon", "Chlorine", "Cadmium"]],
  ["Quel symbole correspond à l'or ?", "Which symbol stands for gold?", "Au", "Au", ["Or", "Ag", "Hg"], ["Or", "Ag", "Hg"]],
  ["Quel symbole correspond au cuivre ?", "Which symbol stands for copper?", "Cu", "Cu", ["Co", "Cr", "Cd"], ["Co", "Cr", "Cd"]],
  // Astronomie (10)
  ["Combien y a-t-il de lunes galiléennes autour de Jupiter ?", "How many Galilean moons orbit Jupiter?", "4", "4", ["2", "6", "10"], ["2", "6", "10"]],
  ["Quel est le plus gros satellite de Jupiter ?", "Largest moon of Jupiter?", "Ganymède", "Ganymede", ["Europe", "Io", "Callisto"], ["Europa", "Io", "Callisto"]],
  ["Quel est le plus gros satellite de Saturne ?", "Largest moon of Saturn?", "Titan", "Titan", ["Encelade", "Mimas", "Rhéa"], ["Enceladus", "Mimas", "Rhea"]],
  ["Comment s'appelle la galaxie voisine la plus proche de la Voie lactée ?", "Closest large galaxy to the Milky Way?", "Andromède", "Andromeda", ["Triangle", "Sombrero", "Cigare"], ["Triangulum", "Sombrero", "Cigar"]],
  ["En quelle année Apollo 11 a-t-elle aluni ?", "When did Apollo 11 land on the Moon?", "1969", "1969", ["1965", "1972", "1957"], ["1965", "1972", "1957"]],
  ["En quelle année a été lancé le télescope Hubble ?", "When was Hubble launched?", "1990", "1990", ["1985", "1995", "2000"], ["1985", "1995", "2000"]],
  ["En quelle année a été lancé le télescope James Webb ?", "When was the James Webb telescope launched?", "2021", "2021", ["2018", "2022", "2024"], ["2018", "2022", "2024"]],
  ["Quelle est la distance moyenne Terre-Soleil ?", "Average Earth–Sun distance?", "150 millions de km", "150 million km", ["100 millions", "200 millions", "300 millions"], ["100 million", "200 million", "300 million"]],
  ["Combien de temps la Lune met-elle pour orbiter la Terre ?", "How long does the Moon orbit Earth?", "27.3 jours", "27.3 days", ["7 jours", "30 jours", "365 jours"], ["7 days", "30 days", "365 days"]],
  ["Quelle est la première sonde sortie du système solaire ?", "First probe to leave the solar system?", "Voyager 1", "Voyager 1", ["Voyager 2", "Pioneer 10", "Cassini"], ["Voyager 2", "Pioneer 10", "Cassini"]],
  // Bio (10)
  ["Quel organe produit la bile ?", "Which organ produces bile?", "Foie", "Liver", ["Pancréas", "Reins", "Estomac"], ["Pancreas", "Kidneys", "Stomach"]],
  ["Quel organe produit l'insuline ?", "Which organ produces insulin?", "Pancréas", "Pancreas", ["Foie", "Reins", "Vésicule biliaire"], ["Liver", "Kidneys", "Gallbladder"]],
  ["Quels organes filtrent le sang ?", "Which organs filter blood?", "Reins", "Kidneys", ["Foie", "Poumons", "Rate"], ["Liver", "Lungs", "Spleen"]],
  ["Quel est l'os le plus long du corps humain ?", "Longest bone in the human body?", "Fémur", "Femur", ["Tibia", "Humérus", "Sternum"], ["Tibia", "Humerus", "Sternum"]],
  ["Quel est le plus petit os du corps humain ?", "Smallest bone in the human body?", "Étrier", "Stapes", ["Marteau", "Enclume", "Os hyoïde"], ["Malleus", "Incus", "Hyoid bone"]],
  ["Combien de lobes a le cerveau humain ?", "How many lobes does the human brain have?", "4", "4", ["2", "3", "6"], ["2", "3", "6"]],
  ["Quel groupe sanguin est donneur universel ?", "Which blood group is universal donor?", "O négatif", "O negative", ["AB positif", "A positif", "B négatif"], ["AB positive", "A positive", "B negative"]],
  ["Quel groupe sanguin est receveur universel ?", "Which blood group is universal receiver?", "AB positif", "AB positive", ["O négatif", "A positif", "B négatif"], ["O negative", "A positive", "B negative"]],
  ["Quel est le plus grand muscle du corps humain ?", "Largest muscle in the human body?", "Grand fessier", "Gluteus maximus", ["Quadriceps", "Latissimus dorsi", "Pectoral"], ["Quadriceps", "Latissimus dorsi", "Pectoral"]],
  ["Combien de paires de chromosomes a un humain ?", "How many chromosome pairs do humans have?", "23", "23", ["22", "24", "46"], ["22", "24", "46"]],
  // Physique (5)
  ["Que dit la 2e loi de Newton ?", "What is Newton's second law?", "F = ma", "F = ma", ["E = mc²", "PV = nRT", "F = -kx"], ["E = mc²", "PV = nRT", "F = -kx"]],
  ["Quelle équation lie énergie et masse selon Einstein ?", "Which equation links energy and mass per Einstein?", "E = mc²", "E = mc²", ["F = ma", "PV = nRT", "λ = h/p"], ["F = ma", "PV = nRT", "λ = h/p"]],
  ["Quelle est la vitesse approximative du son dans l'air ?", "Approximate speed of sound in air?", "343 m/s", "343 m/s", ["1500 m/s", "150 m/s", "300 000 km/s"], ["1500 m/s", "150 m/s", "300,000 km/s"]],
  ["Qui a énoncé la loi de la gravitation universelle ?", "Who stated universal gravitation?", "Isaac Newton", "Isaac Newton", ["Galilée", "Kepler", "Einstein"], ["Galileo", "Kepler", "Einstein"]],
  ["Quel pôle d'un aimant attire le pôle nord ?", "Which pole of a magnet attracts a north pole?", "Le pôle sud", "South pole", ["Le pôle nord", "Aucun", "Cela dépend"], ["North pole", "None", "It depends"]],
  // Maths (5)
  ["Quelle est la valeur approximative de e (Euler) ?", "Approximate value of Euler's e?", "2.72", "2.72", ["3.14", "1.41", "1.62"], ["3.14", "1.41", "1.62"]],
  ["Quelle est la valeur du nombre d'or ?", "Approximate value of the golden ratio?", "1.618", "1.618", ["1.41", "2.72", "3.14"], ["1.41", "2.72", "3.14"]],
  ["Quelle est la racine carrée de 81 ?", "Square root of 81?", "9", "9", ["8", "10", "11"], ["8", "10", "11"]],
  ["Quelle est la somme des angles d'un triangle ?", "Sum of angles in a triangle?", "180°", "180°", ["90°", "270°", "360°"], ["90°", "270°", "360°"]],
  ["Combien font 25 × 4 ?", "What is 25 × 4?", "100", "100", ["75", "125", "20"], ["75", "125", "20"]],
  // Découvertes / nature (10)
  ["Qui a découvert la structure de l'ADN en 1953 ?", "Who discovered the DNA structure in 1953?", "Watson et Crick", "Watson and Crick", ["Mendel seul", "Pauling seul", "Franklin seule"], ["Mendel alone", "Pauling alone", "Franklin alone"]],
  ["Qui a découvert la planète Uranus en 1781 ?", "Who discovered Uranus in 1781?", "William Herschel", "William Herschel", ["Galilée", "Kepler", "Le Verrier"], ["Galileo", "Kepler", "Le Verrier"]],
  ["Qui a découvert le radium ?", "Who discovered radium?", "Marie et Pierre Curie", "Marie and Pierre Curie", ["Henri Becquerel seul", "Ernest Rutherford", "Niels Bohr"], ["Henri Becquerel alone", "Ernest Rutherford", "Niels Bohr"]],
  ["Qui a découvert l'électron ?", "Who discovered the electron?", "J. J. Thomson", "J. J. Thomson", ["Rutherford", "Bohr", "Chadwick"], ["Rutherford", "Bohr", "Chadwick"]],
  ["Qui a découvert la radioactivité ?", "Who discovered radioactivity?", "Henri Becquerel", "Henri Becquerel", ["Marie Curie", "Wilhelm Röntgen", "Pierre Curie"], ["Marie Curie", "Wilhelm Röntgen", "Pierre Curie"]],
  ["Quel est le plus grand reptile au monde ?", "World's largest reptile?", "Crocodile marin", "Saltwater crocodile", ["Crocodile du Nil", "Anaconda vert", "Tortue luth"], ["Nile crocodile", "Green anaconda", "Leatherback turtle"]],
  ["Quel est le plus grand poisson du monde ?", "Largest fish in the world?", "Requin-baleine", "Whale shark", ["Requin pèlerin", "Espadon", "Mola mola"], ["Basking shark", "Swordfish", "Mola mola"]],
  ["Quelle créature marine est considérée la plus venimeuse ?", "Most venomous marine creature?", "Méduse-boîte", "Box jellyfish", ["Pieuvre à anneaux bleus", "Poisson-pierre", "Vive"], ["Blue-ringed octopus", "Stonefish", "Weever"]],
  ["Quel insecte est célèbre pour sa danse codée chez les abeilles ?", "Which insect is famed for its waggle dance?", "Abeille mellifère", "Honeybee", ["Bourdon", "Guêpe", "Frelon"], ["Bumblebee", "Wasp", "Hornet"]],
  ["Quel est le plus rapide insecte volant ?", "Fastest flying insect?", "Libellule", "Dragonfly", ["Abeille", "Sphinx", "Moustique"], ["Bee", "Hawk moth", "Mosquito"]],
];

/* ── Hard (Platine · 1800 ELO) ────────────────────────────────────── */
const hard: CuratedFact[] = [
  // Chimie pointue (10)
  ["Quel élément a pour symbole W ?", "Which element has symbol W?", "Tungstène", "Tungsten", ["Wolfram (synonyme)", "Vanadium", "Yttrium"], ["Wolfram (synonym)", "Vanadium", "Yttrium"]],
  ["Quel élément a pour symbole Sn ?", "Which element has symbol Sn?", "Étain", "Tin", ["Strontium", "Antimoine", "Sélénium"], ["Strontium", "Antimony", "Selenium"]],
  ["Quel est le numéro atomique de l'uranium ?", "Atomic number of uranium?", "92", "92", ["88", "90", "94"], ["88", "90", "94"]],
  ["Quel est le numéro atomique du fer ?", "Atomic number of iron?", "26", "26", ["24", "28", "30"], ["24", "28", "30"]],
  ["Quel élément a le numéro atomique 79 ?", "Which element has atomic number 79?", "Or", "Gold", ["Argent", "Platine", "Mercure"], ["Silver", "Platinum", "Mercury"]],
  ["Quelle est la formule de l'éthanol ?", "Formula for ethanol?", "C2H6O", "C2H6O", ["CH4", "C3H8O", "CH3OH"], ["CH4", "C3H8O", "CH3OH"]],
  ["Quelle est la formule du méthane ?", "Formula for methane?", "CH4", "CH4", ["CH3", "C2H6", "CH4O"], ["CH3", "C2H6", "CH4O"]],
  ["Quelle est la formule de l'ammoniac ?", "Formula for ammonia?", "NH3", "NH3", ["NH4", "N2H4", "HCN"], ["NH4", "N2H4", "HCN"]],
  ["Quel élément est l'épine dorsale des chaînes ADN ?", "Which element is the backbone of DNA chains?", "Carbone", "Carbon", ["Phosphore", "Azote", "Oxygène"], ["Phosphorus", "Nitrogen", "Oxygen"]],
  ["Quel est l'élément le plus abondant dans la croûte terrestre ?", "Most abundant element in Earth's crust?", "Oxygène", "Oxygen", ["Silicium", "Aluminium", "Fer"], ["Silicon", "Aluminum", "Iron"]],
  // Astronomie (10)
  ["Quelle est l'étoile la plus proche du Soleil ?", "Closest star to the Sun?", "Proxima du Centaure", "Proxima Centauri", ["Alpha du Centaure A", "Bêta du Centaure", "Sirius"], ["Alpha Centauri A", "Beta Centauri", "Sirius"]],
  ["À quelle distance se trouve Proxima du Centaure ?", "Distance to Proxima Centauri?", "4.24 années-lumière", "4.24 light-years", ["10 a-l", "1 a-l", "100 a-l"], ["10 ly", "1 ly", "100 ly"]],
  ["Quelle est la planète naine la plus connue ?", "Most well-known dwarf planet?", "Pluton", "Pluto", ["Cérès", "Hauméa", "Éris"], ["Ceres", "Haumea", "Eris"]],
  ["Combien de planètes naines reconnues officiellement ?", "How many officially recognized dwarf planets?", "5", "5", ["4", "6", "9"], ["4", "6", "9"]],
  ["Quelle première exoplanète a été détectée en 1995 autour d'une étoile semblable au Soleil ?", "First exoplanet (1995) around a Sun-like star?", "51 Pegasi b", "51 Pegasi b", ["Kepler-22b", "HD 209458 b", "Gliese 581 c"], ["Kepler-22b", "HD 209458 b", "Gliese 581 c"]],
  ["En quelle année Voyager 1 a-t-elle été lancée ?", "When was Voyager 1 launched?", "1977", "1977", ["1969", "1985", "1990"], ["1969", "1985", "1990"]],
  ["Quel rover a atterri sur Mars en 1997 ?", "Which rover landed on Mars in 1997?", "Sojourner", "Sojourner", ["Spirit", "Opportunity", "Curiosity"], ["Spirit", "Opportunity", "Curiosity"]],
  ["Quel rover a atterri sur Mars en 2021 ?", "Which rover landed on Mars in 2021?", "Perseverance", "Perseverance", ["Curiosity", "Spirit", "Pathfinder"], ["Curiosity", "Spirit", "Pathfinder"]],
  ["Quelle planète a un cycle solaire de 88 jours ?", "Which planet has an 88-day year?", "Mercure", "Mercury", ["Vénus", "Mars", "Jupiter"], ["Venus", "Mars", "Jupiter"]],
  ["Quelle planète tourne sur le côté (axe ~98°) ?", "Which planet rotates on its side (~98° axis)?", "Uranus", "Uranus", ["Neptune", "Saturne", "Vénus"], ["Neptune", "Saturn", "Venus"]],
  // Bio (10)
  ["Combien de cellules a approximativement le corps humain ?", "Approximate cell count in the human body?", "~37 mille milliards (3.7 × 10¹³)", "~37 trillion (3.7 × 10¹³)", ["~10⁹", "~10²⁰", "~10⁶"], ["~10⁹", "~10²⁰", "~10⁶"]],
  ["Combien de gènes possède approximativement l'humain ?", "Approximate human gene count?", "~20 000", "~20,000", ["~5 000", "~100 000", "~50 000"], ["~5,000", "~100,000", "~50,000"]],
  ["Quelle cellule du corps est la plus longue ?", "Longest cell in the body?", "Neurone (motoneurone sciatique)", "Neuron (sciatic motor neuron)", ["Globule rouge", "Hépatocyte", "Adipocyte"], ["Red blood cell", "Hepatocyte", "Adipocyte"]],
  ["Quel ARN porte les acides aminés au ribosome ?", "Which RNA carries amino acids to the ribosome?", "ARNt (ARN de transfert)", "tRNA (transfer RNA)", ["ARNm", "ARNr", "miARN"], ["mRNA", "rRNA", "miRNA"]],
  ["Quelle bactérie est la plus petite cellule vivante connue ?", "Smallest known living cell?", "Mycoplasme", "Mycoplasma", ["E. coli", "Streptocoque", "Listeria"], ["E. coli", "Streptococcus", "Listeria"]],
  ["Qui partage la découverte de la structure de l'ADN avec Watson et Crick (cliché 51) ?", "Whose Photo 51 contributed to the DNA structure discovery?", "Rosalind Franklin", "Rosalind Franklin", ["Maurice Wilkins", "Linus Pauling", "Erwin Chargaff"], ["Maurice Wilkins", "Linus Pauling", "Erwin Chargaff"]],
  ["Quel cycle métabolique transforme l'acide pyruvique en énergie ?", "Which metabolic cycle turns pyruvate into energy?", "Cycle de Krebs", "Krebs cycle", ["Cycle de Calvin", "Glycolyse", "Bêta-oxydation"], ["Calvin cycle", "Glycolysis", "Beta-oxidation"]],
  ["Quelle molécule est la « monnaie énergétique » de la cellule ?", "Which molecule is the cell's 'energy currency'?", "ATP", "ATP", ["ADN", "GTP", "NADH"], ["DNA", "GTP", "NADH"]],
  ["Quelle est la différence principale entre mitose et méiose ?", "Main difference between mitosis and meiosis?", "Mitose = cellules identiques · méiose = gamètes haploïdes", "Mitosis = identical cells · meiosis = haploid gametes", ["Mitose halve les chromosomes", "Méiose ne divise pas le noyau", "Aucune différence"], ["Mitosis halves chromosomes", "Meiosis doesn't split the nucleus", "No difference"]],
  ["Quel virus géant a été découvert en 2003 ?", "Which giant virus was discovered in 2003?", "Mimivirus", "Mimivirus", ["Pithovirus", "Pandoravirus", "Megavirus"], ["Pithovirus", "Pandoravirus", "Megavirus"]],
  // Physique / particules (5)
  ["Que désigne la lettre h en mécanique quantique ?", "What does 'h' represent in quantum mechanics?", "Constante de Planck", "Planck constant", ["Constante de Boltzmann", "Constante d'Avogadro", "Vitesse de la lumière"], ["Boltzmann constant", "Avogadro constant", "Speed of light"]],
  ["Quelle est approximativement la valeur du nombre d'Avogadro ?", "Approximate value of Avogadro's number?", "6.022 × 10²³", "6.022 × 10²³", ["6.022 × 10¹⁰", "1.602 × 10⁻¹⁹", "9.81 × 10²³"], ["6.022 × 10¹⁰", "1.602 × 10⁻¹⁹", "9.81 × 10²³"]],
  ["Qui a découvert le neutron en 1932 ?", "Who discovered the neutron in 1932?", "James Chadwick", "James Chadwick", ["Ernest Rutherford", "Niels Bohr", "Werner Heisenberg"], ["Ernest Rutherford", "Niels Bohr", "Werner Heisenberg"]],
  ["Que décrit la loi de Coulomb ?", "What does Coulomb's law describe?", "Force électrostatique entre charges", "Electrostatic force between charges", ["Mouvement des planètes", "Inertie d'un corps", "Pression d'un gaz"], ["Planetary motion", "Inertia of a body", "Gas pressure"]],
  ["Quel effet Einstein a-t-il expliqué (Nobel 1921) ?", "Which effect did Einstein explain (1921 Nobel)?", "Effet photoélectrique", "Photoelectric effect", ["Relativité générale", "Effet Compton", "Effet Doppler"], ["General relativity", "Compton effect", "Doppler effect"]],
  // Maths (5)
  ["Qui a démontré le dernier théorème de Fermat en 1994 ?", "Who proved Fermat's Last Theorem in 1994?", "Andrew Wiles", "Andrew Wiles", ["Pierre de Fermat", "Grigori Perelman", "Terence Tao"], ["Pierre de Fermat", "Grigori Perelman", "Terence Tao"]],
  ["Quelle conjecture sur les zéros de la fonction zêta n'est toujours pas démontrée ?", "Which Riemann conjecture about zeta zeros is still unproven?", "Hypothèse de Riemann", "Riemann Hypothesis", ["Conjecture de Goldbach", "P vs NP", "Conjecture de Hodge"], ["Goldbach conjecture", "P vs NP", "Hodge conjecture"]],
  ["Quelle conjecture stipule que tout entier pair > 2 est somme de 2 nombres premiers ?", "Which conjecture says every even integer > 2 is sum of two primes?", "Conjecture de Goldbach", "Goldbach conjecture", ["Hypothèse de Riemann", "Conjecture des nombres jumeaux", "Conjecture de Collatz"], ["Riemann Hypothesis", "Twin prime conjecture", "Collatz conjecture"]],
  ["Tous les combien d'années est décernée la médaille Fields ?", "Every how many years is the Fields Medal awarded?", "4 ans", "4 years", ["2 ans", "5 ans", "Annuel"], ["2 years", "5 years", "Annual"]],
  ["Jusqu'à quel âge maximum un mathématicien peut-il recevoir la médaille Fields ?", "Maximum age to win the Fields Medal?", "40 ans", "40", ["30 ans", "50 ans", "Aucune limite"], ["30", "50", "No limit"]],
  // Inventeurs (5)
  ["Qui a inventé le premier vaccin contre la variole ?", "Who invented the first smallpox vaccine?", "Edward Jenner", "Edward Jenner", ["Louis Pasteur", "Robert Koch", "Albert Sabin"], ["Louis Pasteur", "Robert Koch", "Albert Sabin"]],
  ["En quelle année Fleming a-t-il découvert la pénicilline ?", "When did Fleming discover penicillin?", "1928", "1928", ["1918", "1935", "1941"], ["1918", "1935", "1941"]],
  ["Qui a découvert les rayons X en 1895 ?", "Who discovered X-rays in 1895?", "Wilhelm Röntgen", "Wilhelm Röntgen", ["Henri Becquerel", "Marie Curie", "Pierre Curie"], ["Henri Becquerel", "Marie Curie", "Pierre Curie"]],
  ["Qui a inventé la théorie des quanta en 1900 ?", "Who proposed quantum theory in 1900?", "Max Planck", "Max Planck", ["Niels Bohr", "Albert Einstein", "Werner Heisenberg"], ["Niels Bohr", "Albert Einstein", "Werner Heisenberg"]],
  ["Qui a énoncé le principe d'incertitude en mécanique quantique ?", "Who stated the uncertainty principle?", "Werner Heisenberg", "Werner Heisenberg", ["Erwin Schrödinger", "Niels Bohr", "Paul Dirac"], ["Erwin Schrödinger", "Niels Bohr", "Paul Dirac"]],
  // Misc (5)
  ["Quel est le plus grand champignon clonal au monde ?", "Largest clonal fungus in the world?", "Armillaria de l'Oregon", "Armillaria (Oregon)", ["Cordyceps", "Tricholoma", "Aspergillus"], ["Cordyceps", "Tricholoma", "Aspergillus"]],
  ["Quel est le plus vieil arbre vivant identifié ?", "Oldest known living tree?", "Pinus longaeva (Mathusalem)", "Pinus longaeva (Methuselah)", ["Sequoia géant", "Tilleul de Genève", "If des Pyrénées"], ["Giant sequoia", "Geneva linden", "Pyrenean yew"]],
  ["Combien d'années-lumière mesure la Voie lactée environ ?", "Approximate Milky Way diameter (light-years)?", "100 000", "100,000", ["10 000", "1 000 000", "1 000"], ["10,000", "1,000,000", "1,000"]],
  ["Quel astrophysicien britannique a popularisé les trous noirs ?", "Which British astrophysicist popularized black holes?", "Stephen Hawking", "Stephen Hawking", ["Roger Penrose", "Martin Rees", "Brian May"], ["Roger Penrose", "Martin Rees", "Brian May"]],
  ["Quelle particule a été détectée au CERN en 2012 ?", "Which particle was detected at CERN in 2012?", "Boson de Higgs", "Higgs boson", ["Boson W", "Quark top", "Neutrino tau"], ["W boson", "Top quark", "Tau neutrino"]],
];

/* ── Expert (Diamant · 2200 ELO) ──────────────────────────────────── */
const expert: CuratedFact[] = [
  // Chimie pointue (10)
  ["Quel élément a pour symbole Re ?", "Which element has symbol Re?", "Rhénium", "Rhenium", ["Radium", "Rubidium", "Ruthénium"], ["Radium", "Rubidium", "Ruthenium"]],
  ["Quel élément a pour symbole Pd ?", "Which element has symbol Pd?", "Palladium", "Palladium", ["Plomb", "Platine", "Phosphore"], ["Lead", "Platinum", "Phosphorus"]],
  ["Quel élément a pour symbole Hf ?", "Which element has symbol Hf?", "Hafnium", "Hafnium", ["Hélium", "Holmium", "Hydrogène"], ["Helium", "Holmium", "Hydrogen"]],
  ["Quel élément a le numéro atomique 117 ?", "Which element has atomic number 117?", "Tennesse (Ts)", "Tennessine (Ts)", ["Oganesson", "Moscovium", "Livermorium"], ["Oganesson", "Moscovium", "Livermorium"]],
  ["Quel élément a le numéro atomique 118 ?", "Which element has atomic number 118?", "Oganesson (Og)", "Oganesson (Og)", ["Tennesse", "Moscovium", "Nihonium"], ["Tennessine", "Moscovium", "Nihonium"]],
  ["Quel acide est connu comme le « superacide » le plus fort ?", "Which is known as the strongest superacid?", "Acide fluoroantimonique", "Fluoroantimonic acid", ["Acide sulfurique", "Acide nitrique", "Acide chlorhydrique"], ["Sulfuric acid", "Nitric acid", "Hydrochloric acid"]],
  ["Quel catalyseur est utilisé dans le procédé Haber-Bosch ?", "Which catalyst is used in the Haber-Bosch process?", "Fer", "Iron", ["Platine", "Vanadium", "Nickel"], ["Platinum", "Vanadium", "Nickel"]],
  ["Quel pH a l'eau pure à 25°C ?", "pH of pure water at 25°C?", "7", "7", ["6", "8", "5.5"], ["6", "8", "5.5"]],
  ["Quel chimiste russe a élaboré la classification périodique en 1869 ?", "Which Russian chemist classified elements in 1869?", "Mendeleïev", "Mendeleev", ["Lomonossov", "Markovnikov", "Beketov"], ["Lomonosov", "Markovnikov", "Beketov"]],
  ["Quel composé est responsable de la couleur bleue du sang des limules ?", "Which compound makes horseshoe crab blood blue?", "Hémocyanine (cuivre)", "Hemocyanin (copper)", ["Hémoglobine (fer)", "Chlorocruorine", "Hémérythrine"], ["Hemoglobin (iron)", "Chlorocruorin", "Hemerythrin"]],
  // Astronomie (10)
  ["À quelle distance se trouve la galaxie d'Andromède ?", "Distance to Andromeda Galaxy?", "2.5 millions années-lumière", "2.5 million light-years", ["50 000 a-l", "100 millions a-l", "500 millions a-l"], ["50,000 ly", "100 million ly", "500 million ly"]],
  ["Quel trou noir supermassif réside au centre de la Voie lactée ?", "Which supermassive black hole sits at the Milky Way's center?", "Sagittarius A*", "Sagittarius A*", ["M87*", "Cygnus X-1", "Hercules A"], ["M87*", "Cygnus X-1", "Hercules A"]],
  ["Quel premier trou noir a été photographié en 2019 ?", "Which first black hole was imaged in 2019?", "M87*", "M87*", ["Sagittarius A*", "TON 618", "Cygnus X-1"], ["Sagittarius A*", "TON 618", "Cygnus X-1"]],
  ["Quelle première sonde a atterri sur Vénus ?", "Which first probe landed on Venus?", "Venera 7 (1970)", "Venera 7 (1970)", ["Mariner 2", "Magellan", "Pioneer Venus"], ["Mariner 2", "Magellan", "Pioneer Venus"]],
  ["Quelle plus grande lune du système solaire est-elle ?", "Largest moon in the solar system?", "Ganymède", "Ganymede", ["Titan", "Callisto", "Lune"], ["Titan", "Callisto", "Moon"]],
  ["Quelle lune de Saturne possède une atmosphère épaisse ?", "Which Saturnian moon has a thick atmosphere?", "Titan", "Titan", ["Encelade", "Mimas", "Téthys"], ["Enceladus", "Mimas", "Tethys"]],
  ["Quel premier objet interstellaire a-t-on détecté en 2017 ?", "Which first interstellar object was detected in 2017?", "'Oumuamua", "'Oumuamua", ["2I/Borisov", "C/2014 UN271", "Hale-Bopp"], ["2I/Borisov", "C/2014 UN271", "Hale-Bopp"]],
  ["En quelle année est attendu le prochain passage de la comète de Halley ?", "When is the next Halley comet return expected?", "2061", "2061", ["2024", "2050", "2086"], ["2024", "2050", "2086"]],
  ["Quel astronome danois a observé une supernova en 1572 ?", "Which Danish astronomer observed a 1572 supernova?", "Tycho Brahe", "Tycho Brahe", ["Johannes Kepler", "Galilée", "Hipparque"], ["Johannes Kepler", "Galileo", "Hipparchus"]],
  ["Qui a découvert les lois du mouvement des planètes ?", "Who discovered the laws of planetary motion?", "Johannes Kepler", "Johannes Kepler", ["Tycho Brahe", "Galilée", "Copernic"], ["Tycho Brahe", "Galileo", "Copernicus"]],
  // Bio (10)
  ["Qui a co-développé la technique CRISPR-Cas9 ?", "Who co-developed CRISPR-Cas9?", "Charpentier et Doudna", "Charpentier and Doudna", ["Watson et Crick", "Mojica seul", "Zhang seul"], ["Watson and Crick", "Mojica alone", "Zhang alone"]],
  ["Quel premier mammifère cloné est né en 1996 ?", "Which first cloned mammal was born in 1996?", "Brebis Dolly", "Sheep Dolly", ["Vache", "Souris", "Cochon"], ["Cow", "Mouse", "Pig"]],
  ["Qui a réalisé la première transplantation cardiaque humaine en 1967 ?", "Who performed the first human heart transplant in 1967?", "Christiaan Barnard", "Christiaan Barnard", ["Norman Shumway", "Denton Cooley", "Michael DeBakey"], ["Norman Shumway", "Denton Cooley", "Michael DeBakey"]],
  ["Qui est considéré le père de la génétique ?", "Who is considered the father of genetics?", "Gregor Mendel", "Gregor Mendel", ["Charles Darwin", "Thomas Hunt Morgan", "August Weismann"], ["Charles Darwin", "Thomas Hunt Morgan", "August Weismann"]],
  ["Qui a popularisé la théorie de l'endosymbiose ?", "Who popularized endosymbiotic theory?", "Lynn Margulis", "Lynn Margulis", ["Carl Woese", "Stephen Jay Gould", "Richard Dawkins"], ["Carl Woese", "Stephen Jay Gould", "Richard Dawkins"]],
  ["Combien y a-t-il de bases dans l'ADN ?", "How many DNA bases?", "4", "4", ["3", "5", "20"], ["3", "5", "20"]],
  ["Quelles sont les 4 bases de l'ADN ?", "Which are the four DNA bases?", "Adénine, Thymine, Cytosine, Guanine", "Adenine, Thymine, Cytosine, Guanine", ["A, U, C, G", "A, T, U, G", "C, G, T, T"], ["A, U, C, G", "A, T, U, G", "C, G, T, T"]],
  ["Quel champignon ophiocordyceps zombifie les fourmis ?", "Which Ophiocordyceps zombifies ants?", "Ophiocordyceps unilateralis", "Ophiocordyceps unilateralis", ["Cordyceps militaris", "Hirsutella citriformis", "Aspergillus fumigatus"], ["Cordyceps militaris", "Hirsutella citriformis", "Aspergillus fumigatus"]],
  ["Quelle plante détient le plus grand génome connu ?", "Which plant has the largest known genome?", "Paris japonica", "Paris japonica", ["Riz", "Pin", "Maïs"], ["Rice", "Pine", "Maize"]],
  ["Quelle bactérie a permis le code génétique standard chez tous les êtres vivants ?", "Which scientist cracked the genetic code (1961-66)?", "Marshall Nirenberg", "Marshall Nirenberg", ["Har Gobind Khorana", "Robert Holley", "Sydney Brenner"], ["Har Gobind Khorana", "Robert Holley", "Sydney Brenner"]],
  // Physique (5)
  ["Quelle particule fondamentale a une charge fractionnaire ?", "Which fundamental particle has fractional charge?", "Quark", "Quark", ["Lepton", "Boson de jauge", "Photon"], ["Lepton", "Gauge boson", "Photon"]],
  ["Quelle constante sans dimension vaut environ 1/137 ?", "Which dimensionless constant is approximately 1/137?", "Constante de structure fine", "Fine-structure constant", ["Constante cosmologique", "Constante de Planck réduite", "Constante d'Avogadro"], ["Cosmological constant", "Reduced Planck constant", "Avogadro constant"]],
  ["Quel théoricien américain a co-développé la théorie des supercordes ?", "Which American helped develop superstring theory?", "Edward Witten", "Edward Witten", ["Richard Feynman", "Stephen Hawking", "Roger Penrose"], ["Richard Feynman", "Stephen Hawking", "Roger Penrose"]],
  ["À quelle température théorique correspond la limite de Planck ?", "At what theoretical temperature does the Planck scale lie?", "~1.4 × 10³² K", "~1.4 × 10³² K", ["10⁹ K", "10¹⁵ K", "10⁵⁰ K"], ["10⁹ K", "10¹⁵ K", "10⁵⁰ K"]],
  ["Quel premier matériau supraconducteur fut observé en 1911 par Onnes ?", "Which first superconductor was observed by Onnes in 1911?", "Mercure", "Mercury", ["Plomb", "Étain", "Niobium"], ["Lead", "Tin", "Niobium"]],
  // Maths (5)
  ["Qui a démontré la conjecture de Poincaré en 2003 ?", "Who proved the Poincaré conjecture in 2003?", "Grigori Perelman", "Grigori Perelman", ["Andrew Wiles", "Terence Tao", "Maryam Mirzakhani"], ["Andrew Wiles", "Terence Tao", "Maryam Mirzakhani"]],
  ["Qui a démontré le théorème d'incomplétude en 1931 ?", "Who proved the incompleteness theorem in 1931?", "Kurt Gödel", "Kurt Gödel", ["Alan Turing", "Bertrand Russell", "David Hilbert"], ["Alan Turing", "Bertrand Russell", "David Hilbert"]],
  ["Quel cardinal infini désigne le dénombrable ?", "Which infinite cardinal denotes the countable?", "Aleph zéro", "Aleph-null", ["Aleph un", "Aleph oméga", "Beth zéro"], ["Aleph-one", "Aleph-omega", "Beth-zero"]],
  ["Combien de dimensions ont les octonions ?", "How many dimensions do octonions have?", "8", "8", ["4", "16", "2"], ["4", "16", "2"]],
  ["Quel plus grand nombre premier de Mersenne fut découvert en 2018 ?", "Which largest Mersenne prime was found in 2018?", "2^82589933 − 1", "2^82589933 − 1", ["2^77232917 − 1", "2^57885161 − 1", "2^43112609 − 1"], ["2^77232917 − 1", "2^57885161 − 1", "2^43112609 − 1"]],
  // Histoire science (10)
  ["Qui a construit le premier cyclotron en 1931 ?", "Who built the first cyclotron in 1931?", "Ernest Lawrence", "Ernest Lawrence", ["Niels Bohr", "Enrico Fermi", "Wolfgang Pauli"], ["Niels Bohr", "Enrico Fermi", "Wolfgang Pauli"]],
  ["Où le premier réacteur nucléaire a-t-il fonctionné en 1942 ?", "Where did the first nuclear reactor run in 1942?", "Université de Chicago (Chicago Pile-1)", "University of Chicago (Chicago Pile-1)", ["Los Alamos", "Hanford", "Oak Ridge"], ["Los Alamos", "Hanford", "Oak Ridge"]],
  ["En quelle année Apollo 8 a-t-elle orbité la Lune ?", "When did Apollo 8 orbit the Moon?", "1968", "1968", ["1969", "1965", "1972"], ["1969", "1965", "1972"]],
  ["Qui a publié les Principia Mathematica en 1687 ?", "Who published the Principia in 1687?", "Isaac Newton", "Isaac Newton", ["Robert Hooke", "Christiaan Huygens", "Edmond Halley"], ["Robert Hooke", "Christiaan Huygens", "Edmond Halley"]],
  ["Qui a inventé la pile électrique en 1800 ?", "Who invented the electric battery in 1800?", "Alessandro Volta", "Alessandro Volta", ["Luigi Galvani", "Michael Faraday", "Georg Ohm"], ["Luigi Galvani", "Michael Faraday", "Georg Ohm"]],
  ["Qui a découvert les ondes électromagnétiques en 1887 ?", "Who discovered electromagnetic waves in 1887?", "Heinrich Hertz", "Heinrich Hertz", ["James Maxwell", "Marconi", "Edison"], ["James Maxwell", "Marconi", "Edison"]],
  ["Qui a co-énoncé les équations de Maxwell ?", "Who formulated Maxwell's equations?", "James Clerk Maxwell", "James Clerk Maxwell", ["Michael Faraday", "Heinrich Hertz", "Hendrik Lorentz"], ["Michael Faraday", "Heinrich Hertz", "Hendrik Lorentz"]],
  ["Quel premier robot industriel fut commercialisé en 1961 ?", "Which first industrial robot launched in 1961?", "Unimate", "Unimate", ["ASIMO", "Shakey", "PUMA"], ["ASIMO", "Shakey", "PUMA"]],
  ["Quel scientifique français a démontré l'intrication quantique en 1982 ?", "Which French scientist demonstrated quantum entanglement in 1982?", "Alain Aspect", "Alain Aspect", ["Serge Haroche", "Claude Cohen-Tannoudji", "Albert Fert"], ["Serge Haroche", "Claude Cohen-Tannoudji", "Albert Fert"]],
  ["Quel scandale OPERA en 2011 prétendait des neutrinos plus rapides que la lumière ?", "Which 2011 OPERA scandal claimed faster-than-light neutrinos?", "Connexion défectueuse", "Faulty connection", ["Erreur Einstein", "Rayonnement cosmique", "Météorite"], ["Einstein error", "Cosmic ray", "Meteorite"]],
];

export const SCIENCE_QUESTIONS = buildCuratedCategory(
  "science",
  "sci",
  [easy, medium, hard, expert],
);
