import { buildCuratedCategory, type CuratedFact } from "./_builder";

/* ── Easy (Argent · 1000 ELO) ─────────────────────────────────────── */
const easy: CuratedFact[] = [
  // Fondateurs (10)
  ["Qui a fondé Microsoft avec Paul Allen ?", "Who co-founded Microsoft with Paul Allen?", "Bill Gates", "Bill Gates", ["Steve Jobs", "Steve Ballmer", "Larry Ellison"], ["Steve Jobs", "Steve Ballmer", "Larry Ellison"]],
  ["Qui a co-fondé Apple avec Steve Wozniak ?", "Who co-founded Apple with Steve Wozniak?", "Steve Jobs", "Steve Jobs", ["Bill Gates", "Tim Cook", "Larry Page"], ["Bill Gates", "Tim Cook", "Larry Page"]],
  ["Qui a fondé Facebook ?", "Who founded Facebook?", "Mark Zuckerberg", "Mark Zuckerberg", ["Eduardo Saverin", "Sean Parker", "Jack Dorsey"], ["Eduardo Saverin", "Sean Parker", "Jack Dorsey"]],
  ["Qui a fondé Amazon ?", "Who founded Amazon?", "Jeff Bezos", "Jeff Bezos", ["Elon Musk", "Larry Page", "Steve Jobs"], ["Elon Musk", "Larry Page", "Steve Jobs"]],
  ["Qui a co-fondé Twitter avec Biz Stone ?", "Who co-founded Twitter with Biz Stone?", "Jack Dorsey", "Jack Dorsey", ["Mark Zuckerberg", "Evan Williams", "Reid Hoffman"], ["Mark Zuckerberg", "Evan Williams", "Reid Hoffman"]],
  ["Qui a co-fondé Google avec Sergey Brin ?", "Who co-founded Google with Sergey Brin?", "Larry Page", "Larry Page", ["Eric Schmidt", "Sundar Pichai", "Tim Berners-Lee"], ["Eric Schmidt", "Sundar Pichai", "Tim Berners-Lee"]],
  ["Qui a co-fondé Instagram en 2010 ?", "Who co-founded Instagram in 2010?", "Kevin Systrom", "Kevin Systrom", ["Mike Krieger", "Jack Dorsey", "Mark Zuckerberg"], ["Mike Krieger", "Jack Dorsey", "Mark Zuckerberg"]],
  ["Qui dirige Tesla ?", "Who leads Tesla?", "Elon Musk", "Elon Musk", ["Mark Zuckerberg", "Jeff Bezos", "Jensen Huang"], ["Mark Zuckerberg", "Jeff Bezos", "Jensen Huang"]],
  ["Qui dirige actuellement Apple ?", "Who currently leads Apple?", "Tim Cook", "Tim Cook", ["Steve Jobs", "Jony Ive", "Craig Federighi"], ["Steve Jobs", "Jony Ive", "Craig Federighi"]],
  ["Qui a fondé SpaceX ?", "Who founded SpaceX?", "Elon Musk", "Elon Musk", ["Jeff Bezos", "Richard Branson", "Larry Page"], ["Jeff Bezos", "Richard Branson", "Larry Page"]],
  // Acronymes (10)
  ["Que signifie HTTP ?", "What does HTTP stand for?", "HyperText Transfer Protocol", "HyperText Transfer Protocol", ["High Transfer Protocol", "Home Text Transfer Protocol", "Hyper Type Transfer Protocol"], ["High Transfer Protocol", "Home Text Transfer Protocol", "Hyper Type Transfer Protocol"]],
  ["Que signifie HTML ?", "What does HTML stand for?", "HyperText Markup Language", "HyperText Markup Language", ["High Text Manipulation Layer", "HyperText Major Language", "Home Tool Markup Logic"], ["High Text Manipulation Layer", "HyperText Major Language", "Home Tool Markup Logic"]],
  ["Que signifie URL ?", "What does URL stand for?", "Uniform Resource Locator", "Uniform Resource Locator", ["Universal Reference Link", "Unique Routed Link", "User Resource Locator"], ["Universal Reference Link", "Unique Routed Link", "User Resource Locator"]],
  ["Que signifie CPU ?", "What does CPU stand for?", "Central Processing Unit", "Central Processing Unit", ["Computer Personal Unit", "Central Power Unit", "Core Processing Utility"], ["Computer Personal Unit", "Central Power Unit", "Core Processing Utility"]],
  ["Que signifie RAM ?", "What does RAM stand for?", "Random Access Memory", "Random Access Memory", ["Read Access Module", "Random Allocation Memory", "Rapid Access Memory"], ["Read Access Module", "Random Allocation Memory", "Rapid Access Memory"]],
  ["Que signifie PDF ?", "What does PDF stand for?", "Portable Document Format", "Portable Document Format", ["Personal Document File", "Plain Data File", "Print Document Format"], ["Personal Document File", "Plain Data File", "Print Document Format"]],
  ["Que signifie SQL ?", "What does SQL stand for?", "Structured Query Language", "Structured Query Language", ["Standard Query Logic", "System Query Language", "Sequential Query Layer"], ["Standard Query Logic", "System Query Language", "Sequential Query Layer"]],
  ["Que signifie CSS ?", "What does CSS stand for?", "Cascading Style Sheets", "Cascading Style Sheets", ["Computer Styled Syntax", "Coded Style System", "Centralized Style Source"], ["Computer Styled Syntax", "Coded Style System", "Centralized Style Source"]],
  ["Que signifie USB ?", "What does USB stand for?", "Universal Serial Bus", "Universal Serial Bus", ["Universal System Bus", "Unified Serial Bridge", "User Storage Bus"], ["Universal System Bus", "Unified Serial Bridge", "User Storage Bus"]],
  ["Que signifie WWW ?", "What does WWW stand for?", "World Wide Web", "World Wide Web", ["World Wireless Web", "Web Wide World", "Worldwide Wave"], ["World Wireless Web", "Web Wide World", "Worldwide Wave"]],
  // Produits / entreprises (10)
  ["Quelle entreprise fabrique l'iPhone ?", "Which company makes the iPhone?", "Apple", "Apple", ["Samsung", "Google", "Microsoft"], ["Samsung", "Google", "Microsoft"]],
  ["Quelle entreprise fabrique le Galaxy ?", "Which company makes the Galaxy phones?", "Samsung", "Samsung", ["Apple", "Google", "Sony"], ["Apple", "Google", "Sony"]],
  ["Quelle entreprise fabrique la PlayStation ?", "Which company makes the PlayStation?", "Sony", "Sony", ["Microsoft", "Nintendo", "Sega"], ["Microsoft", "Nintendo", "Sega"]],
  ["Quelle entreprise fabrique la Xbox ?", "Which company makes the Xbox?", "Microsoft", "Microsoft", ["Sony", "Nintendo", "Atari"], ["Sony", "Nintendo", "Atari"]],
  ["Quelle entreprise fabrique la Nintendo Switch ?", "Which company makes the Nintendo Switch?", "Nintendo", "Nintendo", ["Sony", "Sega", "Microsoft"], ["Sony", "Sega", "Microsoft"]],
  ["Quelle entreprise édite Microsoft Office ?", "Which company makes Microsoft Office?", "Microsoft", "Microsoft", ["Adobe", "Apple", "Google"], ["Adobe", "Apple", "Google"]],
  ["Quelle entreprise édite Photoshop ?", "Which company makes Photoshop?", "Adobe", "Adobe", ["Microsoft", "Corel", "Autodesk"], ["Microsoft", "Corel", "Autodesk"]],
  ["Quelle entreprise édite Gmail ?", "Which company runs Gmail?", "Google", "Google", ["Microsoft", "Yahoo", "Apple"], ["Microsoft", "Yahoo", "Apple"]],
  ["Quel téléphone Google fabrique ?", "Which phone line does Google make?", "Pixel", "Pixel", ["Galaxy", "Surface", "Nexus One uniquement"], ["Galaxy", "Surface", "Nexus One only"]],
  ["Quel ordinateur Microsoft fabrique ?", "Which computer line does Microsoft make?", "Surface", "Surface", ["Pixel Book", "MacBook", "ThinkPad"], ["Pixelbook", "MacBook", "ThinkPad"]],
  // Inventions (5)
  ["Qui a inventé le World Wide Web ?", "Who invented the World Wide Web?", "Tim Berners-Lee", "Tim Berners-Lee", ["Vint Cerf", "Bill Gates", "Steve Jobs"], ["Vint Cerf", "Bill Gates", "Steve Jobs"]],
  ["Qui a créé Linux ?", "Who created Linux?", "Linus Torvalds", "Linus Torvalds", ["Richard Stallman", "Bill Joy", "Ken Thompson"], ["Richard Stallman", "Bill Joy", "Ken Thompson"]],
  ["Qui a créé le langage Python ?", "Who created Python?", "Guido van Rossum", "Guido van Rossum", ["James Gosling", "Brendan Eich", "Larry Wall"], ["James Gosling", "Brendan Eich", "Larry Wall"]],
  ["Qui a créé le langage Java ?", "Who created Java?", "James Gosling", "James Gosling", ["Bjarne Stroustrup", "Brendan Eich", "Dennis Ritchie"], ["Bjarne Stroustrup", "Brendan Eich", "Dennis Ritchie"]],
  ["Qui a créé JavaScript ?", "Who created JavaScript?", "Brendan Eich", "Brendan Eich", ["James Gosling", "Guido van Rossum", "Yukihiro Matsumoto"], ["James Gosling", "Guido van Rossum", "Yukihiro Matsumoto"]],
  // Tech basiques (10)
  ["Que signifie le S de HTTPS ?", "What does the S in HTTPS mean?", "Secure", "Secure", ["Standard", "Secret", "Server"], ["Standard", "Secret", "Server"]],
  ["En quelle année a été lancé l'iPhone ?", "When was the iPhone launched?", "2007", "2007", ["2005", "2009", "2010"], ["2005", "2009", "2010"]],
  ["Quel système d'exploitation équipe les iPhone ?", "Which OS runs on iPhones?", "iOS", "iOS", ["Android", "macOS", "Windows Mobile"], ["Android", "macOS", "Windows Mobile"]],
  ["Quel système d'exploitation équipe les Mac ?", "Which OS runs on Macs?", "macOS", "macOS", ["Windows", "Linux", "iOS"], ["Windows", "Linux", "iOS"]],
  ["Quel système d'exploitation Google développe pour mobiles ?", "Which mobile OS does Google develop?", "Android", "Android", ["iOS", "Windows Phone", "Symbian"], ["iOS", "Windows Phone", "Symbian"]],
  ["Quel est le moteur de recherche le plus utilisé au monde ?", "Most used search engine worldwide?", "Google", "Google", ["Bing", "Yahoo", "DuckDuckGo"], ["Bing", "Yahoo", "DuckDuckGo"]],
  ["Quel navigateur est le plus utilisé en 2024 ?", "Most used web browser in 2024?", "Chrome", "Chrome", ["Safari", "Firefox", "Edge"], ["Safari", "Firefox", "Edge"]],
  ["Quel site de vidéos a été lancé en 2005 ?", "Which video site launched in 2005?", "YouTube", "YouTube", ["Vimeo", "Dailymotion", "Twitch"], ["Vimeo", "Dailymotion", "Twitch"]],
  ["Quelle plateforme de streaming musical leader est suédoise ?", "Which Swedish music streaming leader?", "Spotify", "Spotify", ["Deezer", "Tidal", "SoundCloud"], ["Deezer", "Tidal", "SoundCloud"]],
  ["Quelle plateforme de streaming vidéo a popularisé Stranger Things ?", "Which streaming platform popularized Stranger Things?", "Netflix", "Netflix", ["Hulu", "Disney+", "Amazon Prime"], ["Hulu", "Disney+", "Amazon Prime"]],
  // Crypto / divers (5)
  ["Quelle cryptomonnaie a été créée en 2009 ?", "Which cryptocurrency launched in 2009?", "Bitcoin", "Bitcoin", ["Ethereum", "Litecoin", "Ripple"], ["Ethereum", "Litecoin", "Ripple"]],
  ["Quel réseau social a popularisé les vidéos courtes en 2018-19 ?", "Which social network popularized short videos in 2018-19?", "TikTok", "TikTok", ["Instagram", "Snapchat", "YouTube Shorts"], ["Instagram", "Snapchat", "YouTube Shorts"]],
  ["Quelle entreprise a racheté Twitter en 2022 ?", "Who bought Twitter in 2022?", "Elon Musk", "Elon Musk", ["Microsoft", "Google", "Meta"], ["Microsoft", "Google", "Meta"]],
  ["Quelle plateforme dédiée au code utilise des dépôts Git ?", "Which Git-based code platform?", "GitHub", "GitHub", ["GitLab", "Bitbucket", "SourceForge"], ["GitLab", "Bitbucket", "SourceForge"]],
  ["Quelle plateforme de questions-réponses pour développeurs est célèbre ?", "Which famous Q&A site for developers?", "Stack Overflow", "Stack Overflow", ["Quora", "Reddit r/programming", "Hacker News"], ["Quora", "Reddit r/programming", "Hacker News"]],
  // Culture internet / créateurs (12)
  ["Quel est le vrai nom de PewDiePie ?", "What's PewDiePie's real name?", "Felix Kjellberg", "Felix Kjellberg", ["Markus Persson", "Anthony Padilla", "Logan Paul"], ["Markus Persson", "Anthony Padilla", "Logan Paul"]],
  ["Quel est le vrai nom de MrBeast ?", "What's MrBeast's real name?", "Jimmy Donaldson", "Jimmy Donaldson", ["Felix Kjellberg", "Logan Paul", "Mark Fischbach"], ["Felix Kjellberg", "Logan Paul", "Mark Fischbach"]],
  ["Quelle entreprise possède Twitch ?", "Who owns Twitch?", "Amazon", "Amazon", ["Google", "Microsoft", "Meta"], ["Google", "Microsoft", "Meta"]],
  ["Quelle entreprise chinoise possède TikTok ?", "Which Chinese company owns TikTok?", "ByteDance", "ByteDance", ["Tencent", "Alibaba", "Baidu"], ["Tencent", "Alibaba", "Baidu"]],
  ["Quelle app est connue pour ses photos éphémères ?", "Which app is famous for self-destructing photos?", "Snapchat", "Snapchat", ["Instagram", "WhatsApp", "Telegram"], ["Instagram", "WhatsApp", "Telegram"]],
  ["Quelle plateforme de chat a été créée à l'origine pour les gamers ?", "Which chat platform was originally built for gamers?", "Discord", "Discord", ["Slack", "Telegram", "Teams"], ["Slack", "Telegram", "Teams"]],
  ["Quelle race de chien est devenue le mème Doge ?", "Which dog breed became the Doge meme?", "Shiba Inu", "Shiba Inu", ["Akita", "Husky", "Corgi"], ["Akita", "Husky", "Corgi"]],
  ["Quelle chanson de Rick Astley sert au Rickroll ?", "Which Rick Astley song is the Rickroll?", "Never Gonna Give You Up", "Never Gonna Give You Up", ["Together Forever", "Whenever You Need Somebody", "Cry for Help"], ["Together Forever", "Whenever You Need Somebody", "Cry for Help"]],
  ["Quel est le prénom du youtubeur Squeezie ?", "What is YouTuber Squeezie's first name?", "Lucas", "Lucas", ["Hugo", "Antoine", "Théo"], ["Hugo", "Antoine", "Théo"]],
  ["Sous quel pseudo Norman Thavaud s'est-il fait connaître ?", "Under which name did Norman Thavaud rise to fame?", "Norman fait des vidéos", "Norman fait des vidéos", ["Cyprien", "Mister V", "Squeezie"], ["Cyprien", "Mister V", "Squeezie"]],
  ["Quelle app de vidéos courtes s'appelait Musical.ly avant 2018 ?", "Which short-video app was called Musical.ly before 2018?", "TikTok", "TikTok", ["Snapchat", "Vine", "Triller"], ["Snapchat", "Vine", "Triller"]],
  ["Sous quel pseudo Jimmy Donaldson est-il connu ?", "What's Jimmy Donaldson's online alias?", "MrBeast", "MrBeast", ["PewDiePie", "Markiplier", "Dream"], ["PewDiePie", "Markiplier", "Dream"]],
];

/* ── Medium (Or · 1400 ELO) ───────────────────────────────────────── */
const medium: CuratedFact[] = [
  // Fondateurs (10)
  ["Qui a fondé Netflix avec Marc Randolph ?", "Who co-founded Netflix with Marc Randolph?", "Reed Hastings", "Reed Hastings", ["Steve Jobs", "Bill Gates", "Larry Page"], ["Steve Jobs", "Bill Gates", "Larry Page"]],
  ["Qui a co-fondé Airbnb ?", "Who co-founded Airbnb?", "Brian Chesky", "Brian Chesky", ["Travis Kalanick", "Daniel Ek", "Reid Hoffman"], ["Travis Kalanick", "Daniel Ek", "Reid Hoffman"]],
  ["Qui a co-fondé Uber ?", "Who co-founded Uber?", "Travis Kalanick", "Travis Kalanick", ["Brian Chesky", "Reid Hoffman", "Daniel Ek"], ["Brian Chesky", "Reid Hoffman", "Daniel Ek"]],
  ["Qui a fondé LinkedIn ?", "Who founded LinkedIn?", "Reid Hoffman", "Reid Hoffman", ["Jack Dorsey", "Brian Chesky", "Eric Schmidt"], ["Jack Dorsey", "Brian Chesky", "Eric Schmidt"]],
  ["Qui a fondé eBay ?", "Who founded eBay?", "Pierre Omidyar", "Pierre Omidyar", ["Jeff Bezos", "Marc Benioff", "Larry Ellison"], ["Jeff Bezos", "Marc Benioff", "Larry Ellison"]],
  ["Qui a fondé Spotify ?", "Who founded Spotify?", "Daniel Ek", "Daniel Ek", ["Sean Parker", "Reid Hoffman", "Markus Persson"], ["Sean Parker", "Reid Hoffman", "Markus Persson"]],
  ["Qui a fondé Snapchat ?", "Who co-founded Snapchat?", "Evan Spiegel", "Evan Spiegel", ["Jack Dorsey", "Mark Zuckerberg", "Brian Acton"], ["Jack Dorsey", "Mark Zuckerberg", "Brian Acton"]],
  ["Qui a co-fondé YouTube avec Steve Chen ?", "Who co-founded YouTube with Steve Chen?", "Chad Hurley", "Chad Hurley", ["Jawed Karim", "Sergey Brin", "Mark Cuban"], ["Jawed Karim", "Sergey Brin", "Mark Cuban"]],
  ["Qui a fondé Reddit avec Steve Huffman ?", "Who co-founded Reddit with Steve Huffman?", "Alexis Ohanian", "Alexis Ohanian", ["Aaron Swartz", "Yishan Wong", "Sam Altman"], ["Aaron Swartz", "Yishan Wong", "Sam Altman"]],
  ["Qui a co-fondé PayPal avec Peter Thiel ?", "Who co-founded PayPal with Peter Thiel?", "Max Levchin", "Max Levchin", ["Reid Hoffman", "Elon Musk", "Tous les précédents"], ["Reid Hoffman", "Elon Musk", "All of the above"]],
  // Langages / créateurs (10)
  ["Qui a créé le langage C ?", "Who created the C language?", "Dennis Ritchie", "Dennis Ritchie", ["Ken Thompson", "Bjarne Stroustrup", "Brian Kernighan"], ["Ken Thompson", "Bjarne Stroustrup", "Brian Kernighan"]],
  ["Qui a créé le langage C++ ?", "Who created C++?", "Bjarne Stroustrup", "Bjarne Stroustrup", ["Dennis Ritchie", "James Gosling", "Linus Torvalds"], ["Dennis Ritchie", "James Gosling", "Linus Torvalds"]],
  ["Qui a créé le langage Ruby ?", "Who created Ruby?", "Yukihiro Matsumoto", "Yukihiro Matsumoto", ["Larry Wall", "Rasmus Lerdorf", "Anders Hejlsberg"], ["Larry Wall", "Rasmus Lerdorf", "Anders Hejlsberg"]],
  ["Qui a créé le langage PHP ?", "Who created PHP?", "Rasmus Lerdorf", "Rasmus Lerdorf", ["Yukihiro Matsumoto", "Larry Wall", "Brendan Eich"], ["Yukihiro Matsumoto", "Larry Wall", "Brendan Eich"]],
  ["Qui a créé le langage Perl ?", "Who created Perl?", "Larry Wall", "Larry Wall", ["Rasmus Lerdorf", "Yukihiro Matsumoto", "Guido van Rossum"], ["Rasmus Lerdorf", "Yukihiro Matsumoto", "Guido van Rossum"]],
  ["Qui a créé le langage Lisp en 1958 ?", "Who created Lisp in 1958?", "John McCarthy", "John McCarthy", ["Marvin Minsky", "Alan Kay", "Donald Knuth"], ["Marvin Minsky", "Alan Kay", "Donald Knuth"]],
  ["Qui a co-créé le langage Go chez Google ?", "Who co-created Go at Google?", "Rob Pike, Ken Thompson, Robert Griesemer", "Rob Pike, Ken Thompson, Robert Griesemer", ["Brendan Eich seul", "Linus Torvalds seul", "Sundar Pichai seul"], ["Brendan Eich alone", "Linus Torvalds alone", "Sundar Pichai alone"]],
  ["Qui a créé le langage Rust à l'origine ?", "Who originally created Rust?", "Graydon Hoare", "Graydon Hoare", ["Steve Klabnik", "Brendan Eich", "Linus Torvalds"], ["Steve Klabnik", "Brendan Eich", "Linus Torvalds"]],
  ["Qui a co-créé Smalltalk ?", "Who co-created Smalltalk?", "Alan Kay", "Alan Kay", ["John McCarthy", "Niklaus Wirth", "Bjarne Stroustrup"], ["John McCarthy", "Niklaus Wirth", "Bjarne Stroustrup"]],
  ["Qui a créé le langage Pascal ?", "Who created Pascal?", "Niklaus Wirth", "Niklaus Wirth", ["Donald Knuth", "Edsger Dijkstra", "Bjarne Stroustrup"], ["Donald Knuth", "Edsger Dijkstra", "Bjarne Stroustrup"]],
  // Dates fondations (5)
  ["En quelle année Microsoft a-t-elle été fondée ?", "When was Microsoft founded?", "1975", "1975", ["1968", "1980", "1984"], ["1968", "1980", "1984"]],
  ["En quelle année Apple a-t-elle été fondée ?", "When was Apple founded?", "1976", "1976", ["1975", "1980", "1984"], ["1975", "1980", "1984"]],
  ["En quelle année Google a-t-elle été fondée ?", "When was Google founded?", "1998", "1998", ["1995", "2000", "2004"], ["1995", "2000", "2004"]],
  ["En quelle année Facebook a-t-il été fondé ?", "When was Facebook founded?", "2004", "2004", ["2002", "2006", "2008"], ["2002", "2006", "2008"]],
  ["En quelle année Amazon a-t-elle été fondée ?", "When was Amazon founded?", "1994", "1994", ["1992", "1996", "1998"], ["1992", "1996", "1998"]],
  // Acronymes (5)
  ["Que signifie API ?", "What does API stand for?", "Application Programming Interface", "Application Programming Interface", ["Advanced Programming Interface", "Application Process Interface", "Active Program Interface"], ["Advanced Programming Interface", "Application Process Interface", "Active Program Interface"]],
  ["Que signifie JSON ?", "What does JSON stand for?", "JavaScript Object Notation", "JavaScript Object Notation", ["JavaScript Online Network", "Java Object Naming", "Joint Standard Object Notation"], ["JavaScript Online Network", "Java Object Naming", "Joint Standard Object Notation"]],
  ["Que signifie XML ?", "What does XML stand for?", "eXtensible Markup Language", "eXtensible Markup Language", ["Extra Markup Language", "X Modular Language", "eXternal Markup Layer"], ["Extra Markup Language", "X Modular Language", "eXternal Markup Layer"]],
  ["Que signifie AJAX ?", "What does AJAX stand for?", "Asynchronous JavaScript and XML", "Asynchronous JavaScript and XML", ["Active JavaScript and XML", "Asynchronous Java Application XML", "Application JavaScript and XHTML"], ["Active JavaScript and XML", "Asynchronous Java Application XML", "Application JavaScript and XHTML"]],
  ["Que signifie FTP ?", "What does FTP stand for?", "File Transfer Protocol", "File Transfer Protocol", ["Fast Transfer Protocol", "File Type Protocol", "Folder Transmit Protocol"], ["Fast Transfer Protocol", "File Type Protocol", "Folder Transmit Protocol"]],
  // Web evolution (5)
  ["En quelle année Tim Berners-Lee a-t-il proposé le Web ?", "When did Tim Berners-Lee propose the Web?", "1989", "1989", ["1985", "1993", "1995"], ["1985", "1993", "1995"]],
  ["Quel premier navigateur populaire est sorti en 1993 ?", "Which popular browser launched in 1993?", "Mosaic", "Mosaic", ["Netscape", "Internet Explorer", "Opera"], ["Netscape", "Internet Explorer", "Opera"]],
  ["En quelle année Wikipédia a-t-elle été lancée ?", "When was Wikipedia launched?", "2001", "2001", ["1999", "2003", "2005"], ["1999", "2003", "2005"]],
  ["En quelle année Netscape a-t-il été lancé ?", "When was Netscape launched?", "1994", "1994", ["1990", "1996", "1998"], ["1990", "1996", "1998"]],
  ["Quel format d'image animée est très utilisé sur le web ?", "Which animated image format is web-popular?", "GIF", "GIF", ["BMP", "TIFF", "RAW"], ["BMP", "TIFF", "RAW"]],
  // OS / hardware (5)
  ["En quelle année Windows 95 est-il sorti ?", "When did Windows 95 release?", "1995", "1995", ["1993", "1997", "1992"], ["1993", "1997", "1992"]],
  ["En quelle année le premier iPad a-t-il été lancé ?", "When was the first iPad launched?", "2010", "2010", ["2007", "2012", "2014"], ["2007", "2012", "2014"]],
  ["Le nom Bluetooth vient d'un roi danois : lequel ?", "Bluetooth is named after which Danish king?", "Harald Ier (Harald Bluetooth)", "Harald I (Harald Bluetooth)", ["Erik le Rouge", "Cnut le Grand", "Harald Hardrada"], ["Erik the Red", "Cnut the Great", "Harald Hardrada"]],
  ["En quelle année le premier microprocesseur Intel 4004 est sorti ?", "When was the Intel 4004 released?", "1971", "1971", ["1965", "1975", "1981"], ["1965", "1975", "1981"]],
  ["En quelle année le premier IBM PC est sorti ?", "When was the first IBM PC released?", "1981", "1981", ["1975", "1984", "1990"], ["1975", "1984", "1990"]],
  // Misc (10)
  ["Qui a co-fondé Wikipédia avec Jimmy Wales ?", "Who co-founded Wikipedia with Jimmy Wales?", "Larry Sanger", "Larry Sanger", ["Sue Gardner", "Aaron Swartz", "Brion Vibber"], ["Sue Gardner", "Aaron Swartz", "Brion Vibber"]],
  ["Que signifie VPN ?", "What does VPN stand for?", "Virtual Private Network", "Virtual Private Network", ["Verified Personal Network", "Volume Private Node", "Virtual Public Net"], ["Verified Personal Network", "Volume Private Node", "Virtual Public Net"]],
  ["Que signifie Tor ?", "What does Tor stand for?", "The Onion Router", "The Onion Router", ["Transit Open Routing", "Token Online Router", "Tunnel of Routes"], ["Transit Open Routing", "Token Online Router", "Tunnel of Routes"]],
  ["Quel format compresse l'audio en supprimant les fréquences inaudibles ?", "Which audio format compresses by removing inaudible ranges?", "MP3", "MP3", ["WAV", "FLAC", "OGG"], ["WAV", "FLAC", "OGG"]],
  ["Quelle technologie sans fil utilise les ondes ~2.4/5 GHz pour le réseau local ?", "Which wireless tech uses 2.4/5 GHz for LAN?", "Wi-Fi", "Wi-Fi", ["Bluetooth", "NFC", "5G"], ["Bluetooth", "NFC", "5G"]],
  ["Quelle est la 2e cryptomonnaie par capitalisation ?", "Second-largest cryptocurrency by market cap?", "Ethereum", "Ethereum", ["Litecoin", "Ripple", "Cardano"], ["Litecoin", "Ripple", "Cardano"]],
  ["Quel système est plus rapide entre SSD et HDD ?", "Which storage is faster, SSD or HDD?", "SSD", "SSD", ["HDD", "Identique", "Cela dépend"], ["HDD", "Same", "It depends"]],
  ["Quel acronyme désigne la mémoire morte ?", "Which acronym means read-only memory?", "ROM", "ROM", ["RAM", "DRAM", "SRAM"], ["RAM", "DRAM", "SRAM"]],
  ["Quelle entreprise possède Instagram ?", "Which company owns Instagram?", "Meta (Facebook)", "Meta (Facebook)", ["Google", "Microsoft", "Amazon"], ["Google", "Microsoft", "Amazon"]],
  ["Quelle entreprise possède YouTube ?", "Which company owns YouTube?", "Google (Alphabet)", "Google (Alphabet)", ["Meta", "Apple", "Microsoft"], ["Meta", "Apple", "Microsoft"]],
  // Créateurs francophones / mèmes (12)
  ["Quel sommet Inoxtag a-t-il escaladé pour son documentaire Kaizen ?", "Which mountain did Inoxtag climb for the Kaizen documentary?", "Everest", "Everest", ["K2", "Mont Blanc", "Kilimandjaro"], ["K2", "Mont Blanc", "Kilimanjaro"]],
  ["Quel évènement de course automobile Squeezie a-t-il créé en 2022 ?", "Which motor-racing event did Squeezie launch in 2022?", "GP Explorer", "GP Explorer", ["ZEvent", "Trackmania World Tour", "Forza Cup"], ["ZEvent", "Trackmania World Tour", "Forza Cup"]],
  ["Quel single de Drake a inspiré le mème des deux poses ?", "Which Drake single inspired the two-pose meme?", "Hotline Bling", "Hotline Bling", ["God's Plan", "In My Feelings", "One Dance"], ["God's Plan", "In My Feelings", "One Dance"]],
  ["Comment s'appelle le mème d'un homme regardant une autre fille devant sa copine ?", "What's the meme of a guy eyeing another woman next to his girlfriend?", "Distracted Boyfriend", "Distracted Boyfriend", ["Roll Safe", "Hide the Pain Harold", "Two Buttons"], ["Roll Safe", "Hide the Pain Harold", "Two Buttons"]],
  ["Quelle vidéaste française est connue pour son podcast 'Canapé Six Places' ?", "Which French creator hosts the podcast 'Canapé Six Places'?", "Léna Situations", "Léna Situations", ["EnjoyPhoenix", "Natoo", "Andy Raconte"], ["EnjoyPhoenix", "Natoo", "Andy Raconte"]],
  ["Quel évènement caritatif annuel ZeratoR organise-t-il ?", "Which annual charity event does ZeratoR run?", "ZEvent", "ZEvent", ["GP Explorer", "Speedons", "Restaus du Cœur Stream"], ["GP Explorer", "Speedons", "Restaus du Cœur Stream"]],
  ["Comment s'appelle le mème d'une fillette rousse souriant devant une maison en feu ?", "What's the meme of a smiling redhead girl in front of a burning house?", "Disaster Girl", "Disaster Girl", ["Bad Luck Brian", "Side Eyeing Chloe", "Success Kid"], ["Bad Luck Brian", "Side Eyeing Chloe", "Success Kid"]],
  ["Quel youtubeur anime 'Le Joueur du Grenier' ?", "Who plays Le Joueur du Grenier?", "Frédéric Molas", "Frédéric Molas", ["Antoine Daniel", "Karim Debbache", "Adrien Ménielle"], ["Antoine Daniel", "Karim Debbache", "Adrien Ménielle"]],
  ["Quel jeu Among Us a explosé en popularité pendant la pandémie ?", "Which game blew up during the pandemic alongside lockdowns?", "Among Us", "Among Us", ["Fall Guys", "Phasmophobia", "Valheim"], ["Fall Guys", "Phasmophobia", "Valheim"]],
  ["Quel mème d'un panneau 'Tout va bien' montre un chien dans une maison en feu ?", "Which 'This Is Fine' meme shows a dog in a burning room?", "This Is Fine", "This Is Fine", ["Disaster Girl", "Bad Luck Brian", "Side Eyeing Chloe"], ["Disaster Girl", "Bad Luck Brian", "Side Eyeing Chloe"]],
  ["Quel youtubeur français a co-créé l'agence d'influenceurs Bump avec Hugo Bonemer ?", "Which French YouTuber co-founded the Bump talent agency?", "Squeezie", "Squeezie", ["Cyprien", "Mister V", "Norman Thavaud"], ["Cyprien", "Mister V", "Norman Thavaud"]],
  ["Quelle plateforme de podcasts vidéo a explosé via Joe Rogan en 2020 ?", "Which podcast platform was supercharged by Joe Rogan in 2020?", "Spotify", "Spotify", ["Apple Podcasts", "Audible", "SoundCloud"], ["Apple Podcasts", "Audible", "SoundCloud"]],
];

/* ── Hard (Platine · 1800 ELO) ────────────────────────────────────── */
const hard: CuratedFact[] = [
  // Pionniers (10)
  ["Qui a envoyé le premier email en 1971 ?", "Who sent the first email in 1971?", "Ray Tomlinson", "Ray Tomlinson", ["Vint Cerf", "Bob Kahn", "Tim Berners-Lee"], ["Vint Cerf", "Bob Kahn", "Tim Berners-Lee"]],
  ["Qui a inventé la souris d'ordinateur ?", "Who invented the computer mouse?", "Douglas Engelbart", "Douglas Engelbart", ["Steve Jobs", "Vint Cerf", "Alan Kay"], ["Steve Jobs", "Vint Cerf", "Alan Kay"]],
  ["Qui a co-inventé le protocole TCP/IP avec Vint Cerf ?", "Who co-invented TCP/IP with Vint Cerf?", "Bob Kahn", "Bob Kahn", ["Ray Tomlinson", "Larry Roberts", "Leonard Kleinrock"], ["Ray Tomlinson", "Larry Roberts", "Leonard Kleinrock"]],
  ["Qui a co-fondé Apple avec Steve Jobs et Wozniak ?", "Who co-founded Apple with Jobs and Woz?", "Ronald Wayne", "Ronald Wayne", ["Mike Markkula", "John Sculley", "Andy Hertzfeld"], ["Mike Markkula", "John Sculley", "Andy Hertzfeld"]],
  ["Qui a inventé l'Ethernet chez Xerox PARC ?", "Who invented Ethernet at Xerox PARC?", "Robert Metcalfe", "Robert Metcalfe", ["Alan Kay", "Charles Thacker", "Butler Lampson"], ["Alan Kay", "Charles Thacker", "Butler Lampson"]],
  ["Quel ordinateur Apple a été conçu par Wozniak en 1976 ?", "Which Apple machine did Wozniak design in 1976?", "Apple I", "Apple I", ["Lisa", "Apple II", "Macintosh"], ["Lisa", "Apple II", "Macintosh"]],
  ["Quel premier ordinateur électronique a été dévoilé en 1945 ?", "Which first electronic computer was unveiled in 1945?", "ENIAC", "ENIAC", ["UNIVAC", "Mark I", "Z3"], ["UNIVAC", "Mark I", "Z3"]],
  ["Quel premier ordinateur personnel a été commercialisé en 1975 ?", "Which first personal computer launched in 1975?", "Altair 8800", "Altair 8800", ["Apple I", "TRS-80", "Commodore PET"], ["Apple I", "TRS-80", "Commodore PET"]],
  ["Quelle femme américaine a popularisé le mot « bug » dans le code ?", "Which American woman popularised 'bug' in computing?", "Grace Hopper", "Grace Hopper", ["Ada Lovelace", "Margaret Hamilton", "Frances Allen"], ["Ada Lovelace", "Margaret Hamilton", "Frances Allen"]],
  ["Qui a écrit Margaret Hamilton du programme Apollo ?", "Margaret Hamilton famously led software for which mission?", "Apollo (NASA)", "Apollo (NASA)", ["Mariner", "Voyager", "Pioneer"], ["Mariner", "Voyager", "Pioneer"]],
  // Langages historiques (5)
  ["Qui a co-développé COBOL en 1959 ?", "Who co-developed COBOL in 1959?", "Grace Hopper", "Grace Hopper", ["John Backus", "Niklaus Wirth", "Donald Knuth"], ["John Backus", "Niklaus Wirth", "Donald Knuth"]],
  ["Qui dirige le développement de Fortran en 1957 chez IBM ?", "Who led Fortran in 1957 at IBM?", "John Backus", "John Backus", ["Grace Hopper", "Marvin Minsky", "Alan Turing"], ["Grace Hopper", "Marvin Minsky", "Alan Turing"]],
  ["Quel langage fonctionnel a Simon Peyton Jones contribué à concevoir ?", "Which functional language did Simon Peyton Jones help design?", "Haskell", "Haskell", ["OCaml", "Erlang", "Scheme"], ["OCaml", "Erlang", "Scheme"]],
  ["Qui a créé Erlang chez Ericsson ?", "Who created Erlang at Ericsson?", "Joe Armstrong", "Joe Armstrong", ["Robert Virding", "Mike Williams", "Tous les trois"], ["Robert Virding", "Mike Williams", "All three"]],
  ["Quel langage fut introduit par Anders Hejlsberg chez Microsoft (2000) ?", "Which language did Anders Hejlsberg introduce at MS in 2000?", "C#", "C#", ["F#", "TypeScript", "Visual Basic .NET"], ["F#", "TypeScript", "Visual Basic .NET"]],
  // Protocoles (5)
  ["En quelle année HTTP/1.1 fut-il standardisé ?", "When was HTTP/1.1 standardized?", "1997", "1997", ["1991", "1995", "2000"], ["1991", "1995", "2000"]],
  ["Quel système de noms a été inventé en 1983 par Paul Mockapetris ?", "Which 1983 system was invented by Paul Mockapetris?", "DNS", "DNS", ["TCP", "FTP", "ARP"], ["TCP", "FTP", "ARP"]],
  ["En quelle année SSL 3.0 a-t-il été publié ?", "When was SSL 3.0 published?", "1996", "1996", ["1990", "1999", "2003"], ["1990", "1999", "2003"]],
  ["Quel protocole a remplacé SSL avec TLS 1.0 ?", "Which protocol replaced SSL as TLS 1.0?", "TLS", "TLS", ["IPsec", "SSH", "PGP"], ["IPsec", "SSH", "PGP"]],
  ["TLS 1.3 a été standardisé en quelle année ?", "When was TLS 1.3 standardized?", "2018", "2018", ["2014", "2020", "2016"], ["2014", "2020", "2016"]],
  // Acquisitions / events (8)
  ["En quelle année Disney a-t-il racheté Pixar ?", "When did Disney acquire Pixar?", "2006", "2006", ["2002", "2009", "2012"], ["2002", "2009", "2012"]],
  ["En quelle année Facebook a-t-il racheté Instagram ?", "When did Facebook acquire Instagram?", "2012", "2012", ["2010", "2014", "2008"], ["2010", "2014", "2008"]],
  ["En quelle année Facebook a-t-il racheté WhatsApp ?", "When did Facebook acquire WhatsApp?", "2014", "2014", ["2012", "2016", "2018"], ["2012", "2016", "2018"]],
  ["En quelle année Google a-t-il racheté YouTube ?", "When did Google acquire YouTube?", "2006", "2006", ["2004", "2008", "2010"], ["2004", "2008", "2010"]],
  ["En quelle année Microsoft a-t-il racheté Skype ?", "When did Microsoft acquire Skype?", "2011", "2011", ["2007", "2014", "2018"], ["2007", "2014", "2018"]],
  ["En quelle année Microsoft a-t-il racheté GitHub ?", "When did Microsoft acquire GitHub?", "2018", "2018", ["2014", "2016", "2020"], ["2014", "2016", "2020"]],
  ["En quelle année Microsoft a-t-il racheté LinkedIn ?", "When did Microsoft acquire LinkedIn?", "2016", "2016", ["2012", "2014", "2018"], ["2012", "2014", "2018"]],
  ["En quelle année Adobe a-t-il racheté Macromedia (Flash) ?", "When did Adobe buy Macromedia (Flash)?", "2005", "2005", ["2001", "2007", "2010"], ["2001", "2007", "2010"]],
  // Crypto / sécurité (5)
  ["Qui a publié le whitepaper Bitcoin en 2008 ?", "Who published the Bitcoin whitepaper in 2008?", "Satoshi Nakamoto", "Satoshi Nakamoto", ["Hal Finney", "Vitalik Buterin", "Nick Szabo"], ["Hal Finney", "Vitalik Buterin", "Nick Szabo"]],
  ["Qui a fondé Ethereum en 2015 ?", "Who founded Ethereum in 2015?", "Vitalik Buterin", "Vitalik Buterin", ["Charles Hoskinson", "Gavin Wood", "Joseph Lubin"], ["Charles Hoskinson", "Gavin Wood", "Joseph Lubin"]],
  ["Quel cryptographe a inventé le concept de smart contract ?", "Who introduced the smart contract concept?", "Nick Szabo", "Nick Szabo", ["Hal Finney", "Wei Dai", "David Chaum"], ["Hal Finney", "Wei Dai", "David Chaum"]],
  ["Quel algorithme de hash Bitcoin utilise-t-il pour le PoW ?", "Which hash function does Bitcoin PoW use?", "SHA-256", "SHA-256", ["MD5", "SHA-1", "Scrypt"], ["MD5", "SHA-1", "Scrypt"]],
  ["Quel algo asymétrique a été publié en 1977 par Rivest, Shamir, Adleman ?", "Which asymmetric cipher did RSA authors publish in 1977?", "RSA", "RSA", ["DES", "AES", "ElGamal"], ["DES", "AES", "ElGamal"]],
  // Concepts info (7)
  ["Qui a popularisé le tri rapide (quicksort) ?", "Who popularized Quicksort?", "Tony Hoare", "Tony Hoare", ["Donald Knuth", "Edsger Dijkstra", "Niklaus Wirth"], ["Donald Knuth", "Edsger Dijkstra", "Niklaus Wirth"]],
  ["Quel logicien a formulé le test de Turing en 1950 ?", "Who proposed the Turing Test (1950)?", "Alan Turing", "Alan Turing", ["John von Neumann", "Claude Shannon", "Marvin Minsky"], ["John von Neumann", "Claude Shannon", "Marvin Minsky"]],
  ["Quel mathématicien a posé la question P vs NP en 1971 ?", "Who formulated P vs NP in 1971?", "Stephen Cook", "Stephen Cook", ["Richard Karp", "Leonid Levin", "Donald Knuth"], ["Richard Karp", "Leonid Levin", "Donald Knuth"]],
  ["Qui a publié l'algèbre de Boole en 1854 ?", "Who published Boolean algebra in 1854?", "George Boole", "George Boole", ["Augustus De Morgan", "Charles Babbage", "Bertrand Russell"], ["Augustus De Morgan", "Charles Babbage", "Bertrand Russell"]],
  ["Quel architecte a défini l'architecture qui sépare CPU et mémoire ?", "Which scientist defined the modern computer architecture?", "John von Neumann", "John von Neumann", ["Alan Turing", "Claude Shannon", "Norbert Wiener"], ["Alan Turing", "Claude Shannon", "Norbert Wiener"]],
  ["Qui a inventé le concept de machine de Turing ?", "Who proposed the Turing machine?", "Alan Turing", "Alan Turing", ["Alonzo Church", "Kurt Gödel", "Emil Post"], ["Alonzo Church", "Kurt Gödel", "Emil Post"]],
  ["Quel théoricien a inventé la théorie de l'information ?", "Who founded information theory?", "Claude Shannon", "Claude Shannon", ["Alan Turing", "Norbert Wiener", "John von Neumann"], ["Alan Turing", "Norbert Wiener", "John von Neumann"]],
  // Compléments hard (10)
  ["En quelle année Java a-t-il été lancé par Sun ?", "When was Java released by Sun?", "1995", "1995", ["1991", "1998", "2001"], ["1991", "1998", "2001"]],
  ["En quelle année Python 3 a-t-il été publié ?", "When was Python 3 released?", "2008", "2008", ["2005", "2011", "2014"], ["2005", "2011", "2014"]],
  ["Quel langage de Microsoft a été lancé en 2012 ?", "Which Microsoft language launched in 2012?", "TypeScript", "TypeScript", ["F#", "C#", "PowerShell"], ["F#", "C#", "PowerShell"]],
  ["Quel framework JavaScript de Facebook est né en 2013 ?", "Which Facebook JS framework launched in 2013?", "React", "React", ["Angular", "Vue", "Ember"], ["Angular", "Vue", "Ember"]],
  ["Quel OS mobile était dominant avant l'iPhone ?", "Which mobile OS was dominant before the iPhone?", "Symbian", "Symbian", ["Palm OS", "BlackBerry OS", "Windows Mobile"], ["Palm OS", "BlackBerry OS", "Windows Mobile"]],
  ["En quelle année Linux 1.0 a-t-il été publié ?", "When was Linux 1.0 released?", "1994", "1994", ["1991", "1996", "1999"], ["1991", "1996", "1999"]],
  ["Quel premier moteur de recherche populaire fut lancé en 1994 ?", "Which popular search engine launched in 1994?", "Yahoo!", "Yahoo!", ["AltaVista", "Lycos", "Excite"], ["AltaVista", "Lycos", "Excite"]],
  ["Quel format vidéo standard a remplacé le H.263 ?", "Which video codec replaced H.263?", "H.264 (AVC)", "H.264 (AVC)", ["VP8", "AV1", "MPEG-2"], ["VP8", "AV1", "MPEG-2"]],
  ["Quel SGBD open-source dirigé par Oracle est très utilisé ?", "Which Oracle-owned open-source DB is widely used?", "MySQL", "MySQL", ["PostgreSQL", "SQLite", "MariaDB"], ["PostgreSQL", "SQLite", "MariaDB"]],
  ["Quelle méthode d'IA a marqué AlphaGo en 2016 ?", "Which AI method powered AlphaGo in 2016?", "Apprentissage par renforcement profond", "Deep reinforcement learning", ["Algorithmes génétiques", "Logique floue", "Systèmes experts"], ["Genetic algorithms", "Fuzzy logic", "Expert systems"]],
  // Histoire des plateformes / mèmes anciens (12)
  ["Quelle chanson roumaine est devenue le mème 'Numa Numa' en 2004 ?", "Which Romanian song became the 'Numa Numa' meme in 2004?", "Dragostea Din Tei", "Dragostea Din Tei", ["Ma Ya Hi", "Mai Ai Hee", "Crazy Frog"], ["Ma Ya Hi", "Mai Ai Hee", "Crazy Frog"]],
  ["Quelle entreprise a racheté Vine avant son lancement en 2013 ?", "Who bought Vine before its 2013 launch?", "Twitter", "Twitter", ["Facebook", "Google", "Yahoo"], ["Facebook", "Google", "Yahoo"]],
  ["Quel réseau social pré-Facebook a été lancé en 2003 par Tom Anderson ?", "Which pre-Facebook social network launched in 2003?", "MySpace", "MySpace", ["Friendster", "Orkut", "hi5"], ["Friendster", "Orkut", "hi5"]],
  ["Quelle vidéo de Despacito ou Baby Shark détient le record YouTube ?", "Which video holds the all-time YouTube view record?", "Baby Shark Dance", "Baby Shark Dance", ["Despacito", "See You Again", "Gangnam Style"], ["Despacito", "See You Again", "Gangnam Style"]],
  ["Comment s'appelle le service originel à partir duquel Twitch a été lancé en 2011 ?", "Which 2007 platform did Twitch spin off from in 2011?", "Justin.tv", "Justin.tv", ["Ustream", "Stickam", "Livestream.com"], ["Ustream", "Stickam", "Livestream.com"]],
  ["En quelle année PewDiePie a-t-il atteint 100 M d'abonnés YouTube ?", "When did PewDiePie hit 100M YouTube subscribers?", "2019", "2019", ["2017", "2018", "2020"], ["2017", "2018", "2020"]],
  ["Qui a créé Reddit en 2005 avec Steve Huffman ?", "Who co-founded Reddit with Steve Huffman in 2005?", "Alexis Ohanian", "Alexis Ohanian", ["Aaron Swartz", "Christopher Slowe", "Yishan Wong"], ["Aaron Swartz", "Christopher Slowe", "Yishan Wong"]],
  ["Quelle chaîne indienne PewDiePie a-t-il combattue pour la 1re place ?", "Which Indian channel did PewDiePie battle for the #1 spot?", "T-Series", "T-Series", ["SET India", "Zee Music", "Cocomelon"], ["SET India", "Zee Music", "Cocomelon"]],
  ["Quelle marque détient l'iconique mème 'Drakeposting' via une chanson ?", "Which artist's song spawned the 'Drakeposting' meme template?", "Drake", "Drake", ["Kanye West", "Travis Scott", "The Weeknd"], ["Kanye West", "Travis Scott", "The Weeknd"]],
  ["Quel vidéaste américain a popularisé en 2007 la vidéo 'Charlie Bit My Finger' ?", "Whose home video became 2007 viral hit 'Charlie Bit My Finger'?", "Howard Davies-Carr", "Howard Davies-Carr", ["Casey Neistat", "Logan Paul", "Jake Paul"], ["Casey Neistat", "Logan Paul", "Jake Paul"]],
  ["Quel défi viral de 2014 a levé des fonds pour la SLA (ALS) ?", "Which 2014 viral challenge raised funds for ALS?", "Ice Bucket Challenge", "Ice Bucket Challenge", ["Mannequin Challenge", "Cinnamon Challenge", "Harlem Shake"], ["Mannequin Challenge", "Cinnamon Challenge", "Harlem Shake"]],
  ["Quel mème de 2010 met en scène un bébé tendant le poing au bord de la mer ?", "Which 2010 meme is a fist-pumping baby on a beach?", "Success Kid", "Success Kid", ["Bad Luck Brian", "Disaster Girl", "Scumbag Steve"], ["Bad Luck Brian", "Disaster Girl", "Scumbag Steve"]],
];

/* ── Expert (Diamant · 2200 ELO) ──────────────────────────────────── */
const expert: CuratedFact[] = [
  // Pionniers profonds (10)
  ["Qui a écrit le premier programme pour la machine analytique de Babbage ?", "Who wrote the first program for Babbage's Analytical Engine?", "Ada Lovelace", "Ada Lovelace", ["Charles Babbage lui-même", "Joseph Marie Jacquard", "Howard Aiken"], ["Charles Babbage himself", "Joseph Marie Jacquard", "Howard Aiken"]],
  ["Quel premier ordinateur à programme stocké est mis en marche en 1948 ?", "First stored-program computer to run (1948)?", "Manchester Baby", "Manchester Baby", ["EDVAC", "EDSAC", "Z4"], ["EDVAC", "EDSAC", "Z4"]],
  ["Qui a co-conçu UNIX en 1969 ?", "Who co-designed Unix in 1969?", "Ken Thompson et Dennis Ritchie", "Ken Thompson and Dennis Ritchie", ["Brian Kernighan seul", "Bill Joy seul", "Linus Torvalds seul"], ["Brian Kernighan alone", "Bill Joy alone", "Linus Torvalds alone"]],
  ["Quel premier message ARPANET fut envoyé en 1969 ?", "What was ARPANET's first transmitted text in 1969?", "« lo » (login interrompu)", "'lo' (interrupted login)", ["« hello world »", "« @ »", "« start »"], ["'hello world'", "'@'", "'start'"]],
  ["Quel ordinateur allemand de Konrad Zuse fut opérationnel en 1941 ?", "Which Konrad Zuse machine ran in 1941?", "Z3", "Z3", ["Z1", "Z4", "Z22"], ["Z1", "Z4", "Z22"]],
  ["Quel laboratoire Xerox a inventé l'interface graphique en 1973 ?", "Which Xerox lab invented the GUI in 1973?", "Xerox PARC", "Xerox PARC", ["Bell Labs", "MIT AI Lab", "SRI International"], ["Bell Labs", "MIT AI Lab", "SRI International"]],
  ["Quel ordinateur Xerox de 1973 avait la première interface fenêtrée ?", "Which 1973 Xerox computer had the first windowed GUI?", "Xerox Alto", "Xerox Alto", ["Xerox Star", "Xerox Sigma", "Xerox 8010"], ["Xerox Star", "Xerox Sigma", "Xerox 8010"]],
  ["Qui a inventé le premier transistor (Bell Labs 1947) ?", "Who invented the first transistor (Bell Labs 1947)?", "Shockley, Bardeen et Brattain", "Shockley, Bardeen and Brattain", ["Robert Noyce seul", "William Shockley seul", "Jack Kilby seul"], ["Robert Noyce alone", "William Shockley alone", "Jack Kilby alone"]],
  ["Qui a inventé le premier laser opérationnel en 1960 ?", "Who built the first operational laser in 1960?", "Theodore Maiman", "Theodore Maiman", ["Charles Townes", "Arthur Schawlow", "Gordon Gould"], ["Charles Townes", "Arthur Schawlow", "Gordon Gould"]],
  ["Qui a co-inventé le circuit intégré en 1958 ?", "Who co-invented the integrated circuit in 1958?", "Jack Kilby et Robert Noyce", "Jack Kilby and Robert Noyce", ["Gordon Moore seul", "William Shockley seul", "Andrew Grove seul"], ["Gordon Moore alone", "William Shockley alone", "Andrew Grove alone"]],
  // Langages pointus (5)
  ["Qui a créé Smalltalk-72 chez Xerox PARC ?", "Who created Smalltalk-72 at Xerox PARC?", "Alan Kay", "Alan Kay", ["Adele Goldberg", "Dan Ingalls", "Butler Lampson"], ["Adele Goldberg", "Dan Ingalls", "Butler Lampson"]],
  ["Qui a créé le langage Prolog en 1972 ?", "Who created Prolog in 1972?", "Alain Colmerauer", "Alain Colmerauer", ["Robert Kowalski", "John McCarthy", "Marvin Minsky"], ["Robert Kowalski", "John McCarthy", "Marvin Minsky"]],
  ["Qui a co-créé Simula 67 (orienté objet) ?", "Who co-created Simula 67 (object-oriented)?", "Ole-Johan Dahl et Kristen Nygaard", "Ole-Johan Dahl and Kristen Nygaard", ["Bjarne Stroustrup", "Alan Kay seul", "Tony Hoare seul"], ["Bjarne Stroustrup", "Alan Kay alone", "Tony Hoare alone"]],
  ["Qui a inventé le langage APL ?", "Who invented APL?", "Kenneth Iverson", "Kenneth Iverson", ["John McCarthy", "Niklaus Wirth", "Donald Knuth"], ["John McCarthy", "Niklaus Wirth", "Donald Knuth"]],
  ["Qui a inventé le pattern Self (langage prototype) ?", "Who created the Self language (prototype-based)?", "David Ungar et Randy Smith", "David Ungar and Randy Smith", ["Alan Kay", "Brendan Eich", "Ken Thompson"], ["Alan Kay", "Brendan Eich", "Ken Thompson"]],
  // Algorithmes / crypto (5)
  ["Quel algorithme de cryptographie a remplacé DES en 2001 ?", "Which cipher replaced DES in 2001?", "AES (Rijndael)", "AES (Rijndael)", ["RC4", "Blowfish", "Twofish"], ["RC4", "Blowfish", "Twofish"]],
  ["Qui a publié le protocole d'échange de clés en 1976 ?", "Who published the key-exchange protocol in 1976?", "Whitfield Diffie et Martin Hellman", "Whitfield Diffie and Martin Hellman", ["Ron Rivest seul", "Adi Shamir seul", "Leonard Adleman seul"], ["Ron Rivest alone", "Adi Shamir alone", "Leonard Adleman alone"]],
  ["En quelle année des collisions ont-elles été démontrées sur SHA-1 ?", "When were SHA-1 collisions demonstrated?", "2017 (SHAttered, Google)", "2017 (SHAttered, Google)", ["2005 (théorique)", "2010", "2020"], ["2005 (theoretical)", "2010", "2020"]],
  ["Quel cryptosystème elliptique est largement utilisé aujourd'hui ?", "Which elliptic-curve cryptosystem is widely used?", "ECDSA / ECDH", "ECDSA / ECDH", ["DSA classique", "RSA", "ElGamal"], ["Classic DSA", "RSA", "ElGamal"]],
  ["Quel ver informatique a marqué internet en 1988 ?", "Which 1988 worm shocked the early internet?", "Morris Worm", "Morris Worm", ["Code Red", "ILOVEYOU", "Slammer"], ["Code Red", "ILOVEYOU", "Slammer"]],
  // Histoire informatique (8)
  ["Quel premier ordinateur français commercial date de 1957 ?", "Which first French commercial computer dates 1957?", "Bull Gamma 3", "Bull Gamma 3", ["Iris 50", "CII Mitra", "BCC 500"], ["Iris 50", "CII Mitra", "BCC 500"]],
  ["Quelle compagnie produisit l'IBM 360 (1964) ?", "Which company produced the IBM 360 (1964)?", "IBM", "IBM", ["Burroughs", "DEC", "Univac"], ["Burroughs", "DEC", "Univac"]],
  ["Qui a développé Multics au MIT (1960s) ?", "Which 1960s OS came out of MIT/Bell Labs/GE?", "Multics", "Multics", ["TOPS-20", "TENEX", "ITS"], ["TOPS-20", "TENEX", "ITS"]],
  ["Quel système BSD est issu d'UC Berkeley ?", "Which BSD variant comes from UC Berkeley?", "4BSD", "4BSD", ["FreeBSD seul", "OpenBSD seul", "NetBSD seul"], ["FreeBSD only", "OpenBSD only", "NetBSD only"]],
  ["Quel premier site web fut hébergé au CERN ?", "Which first website was hosted at CERN?", "info.cern.ch", "info.cern.ch", ["www.example.com", "ncsa.uiuc.edu", "ietf.org"], ["www.example.com", "ncsa.uiuc.edu", "ietf.org"]],
  ["Qui a co-conçu l'architecture du PowerPC dans les années 1990 ?", "Who co-designed the PowerPC architecture in the 1990s?", "Alliance AIM (Apple, IBM, Motorola)", "AIM Alliance (Apple, IBM, Motorola)", ["Intel et HP seuls", "ARM seul", "DEC seul"], ["Intel and HP only", "ARM only", "DEC only"]],
  ["Qui a inventé l'algorithme PageRank ?", "Who invented the PageRank algorithm?", "Larry Page et Sergey Brin", "Larry Page and Sergey Brin", ["Eric Schmidt", "Tim Berners-Lee", "Vint Cerf"], ["Eric Schmidt", "Tim Berners-Lee", "Vint Cerf"]],
  ["Quel premier ver utilisable d'auto-réplication a-t-il marqué Bell Labs ?", "Which seminal self-replicating worm came from Bell Labs?", "Creeper (1971)", "Creeper (1971)", ["Reaper", "Brain", "Elk Cloner"], ["Reaper", "Brain", "Elk Cloner"]],
  // Standards / protocoles (5)
  ["Quel RFC définit IP en 1981 ?", "Which RFC defines IP (1981)?", "RFC 791", "RFC 791", ["RFC 793", "RFC 1122", "RFC 822"], ["RFC 793", "RFC 1122", "RFC 822"]],
  ["Quel RFC définit TCP en 1981 ?", "Which RFC defines TCP (1981)?", "RFC 793", "RFC 793", ["RFC 791", "RFC 854", "RFC 1122"], ["RFC 791", "RFC 854", "RFC 1122"]],
  ["Quel RFC standardise WebSocket en 2011 ?", "Which RFC standardized WebSocket in 2011?", "RFC 6455", "RFC 6455", ["RFC 5246", "RFC 7230", "RFC 8446"], ["RFC 5246", "RFC 7230", "RFC 8446"]],
  ["Quel RFC standardise SMTP (1982) ?", "Which RFC standardized SMTP (1982)?", "RFC 821", "RFC 821", ["RFC 1939", "RFC 3501", "RFC 5321"], ["RFC 1939", "RFC 3501", "RFC 5321"]],
  ["Quel RFC standardise HTTP/2 ?", "Which RFC standardized HTTP/2?", "RFC 7540", "RFC 7540", ["RFC 2616", "RFC 9110", "RFC 9114"], ["RFC 2616", "RFC 9110", "RFC 9114"]],
  // Misc (12)
  ["JavaScript fut conçu en combien de jours par Brendan Eich ?", "JavaScript was prototyped in how many days by Brendan Eich?", "10 jours", "10 days", ["3 mois", "1 mois", "1 jour"], ["3 months", "1 month", "1 day"]],
  ["Qui a proposé CSS en 1994 chez le CERN ?", "Who proposed CSS in 1994 at CERN?", "Håkon Wium Lie", "Håkon Wium Lie", ["Tim Berners-Lee", "Bert Bos", "Brendan Eich"], ["Tim Berners-Lee", "Bert Bos", "Brendan Eich"]],
  ["En quelle année HTML5 a-t-il été finalisé ?", "When was HTML5 finalized?", "2014", "2014", ["2008", "2011", "2017"], ["2008", "2011", "2017"]],
  ["Quel format vectoriel ouvert standard du Web a été standardisé en 2001 ?", "Which open vector format was standardized for the Web in 2001?", "SVG", "SVG", ["EPS", "WMF", "AI"], ["EPS", "WMF", "AI"]],
  ["Quel architecte a co-conçu l'architecture x86 (Intel 8086) ?", "Who co-designed the x86 architecture (Intel 8086)?", "Stephen Morse", "Stephen Morse", ["Andy Grove", "Federico Faggin", "Gordon Moore"], ["Andy Grove", "Federico Faggin", "Gordon Moore"]],
  ["Quelle entreprise britannique a conçu l'architecture ARM ?", "Which British company designed the ARM architecture?", "Acorn Computers", "Acorn Computers", ["Sinclair", "BBC Micro Group", "ARM Holdings dès l'origine"], ["Sinclair", "BBC Micro Group", "ARM Holdings from day one"]],
  ["Quelle norme Wi-Fi a été ratifiée en 1997 ?", "Which Wi-Fi standard was ratified in 1997?", "802.11 (originel)", "802.11 (original)", ["802.11a", "802.11g", "802.11n"], ["802.11a", "802.11g", "802.11n"]],
  ["Qui a co-créé NeXT Computer en 1985 ?", "Who founded NeXT Computer in 1985?", "Steve Jobs", "Steve Jobs", ["Tim Cook", "John Sculley", "Steve Wozniak"], ["Tim Cook", "John Sculley", "Steve Wozniak"]],
  ["Quel modèle d'OS NeXT a influencé macOS X ?", "Which NeXT OS influenced macOS X?", "NeXTSTEP", "NeXTSTEP", ["A/UX", "Mach Kernel seul", "Copland"], ["A/UX", "Mach Kernel only", "Copland"]],
  ["Quel premier appareil à écran tactile capacitif grand public est sorti en 2007 ?", "Which first mass-market capacitive touchscreen device launched in 2007?", "iPhone", "iPhone", ["iPad", "BlackBerry Storm", "HTC Dream"], ["iPad", "BlackBerry Storm", "HTC Dream"]],
  ["Quel premier App Store a ouvert en 2008 ?", "Which app store opened first in 2008?", "App Store (Apple)", "App Store (Apple)", ["Google Play", "Windows Store", "BlackBerry App World"], ["Google Play", "Windows Store", "BlackBerry App World"]],
  ["Quel chercheur a inventé l'algorithme de Dijkstra ?", "Who invented Dijkstra's algorithm?", "Edsger Dijkstra", "Edsger Dijkstra", ["Robert Floyd", "Donald Knuth", "Tony Hoare"], ["Robert Floyd", "Donald Knuth", "Tony Hoare"]],
  // Compléments expert (5)
  ["Quel article de 1965 a énoncé la « loi » prédisant le doublement des transistors ?", "Whose 1965 paper stated the law predicting transistor doubling?", "Gordon Moore", "Gordon Moore", ["Robert Noyce", "Andy Grove", "Federico Faggin"], ["Robert Noyce", "Andy Grove", "Federico Faggin"]],
  ["Quel premier ordinateur d'IBM utilisait des relais (Mark I, 1944) ?", "Which 1944 IBM relay computer was the Mark I?", "Harvard Mark I", "Harvard Mark I", ["Colossus", "Z3", "ENIAC"], ["Colossus", "Z3", "ENIAC"]],
  ["Quel modèle théorique d'Alonzo Church précède la machine de Turing ?", "Which Alonzo Church model preceded the Turing machine?", "Lambda-calcul", "Lambda calculus", ["Algèbre de Boole", "Calcul des prédicats", "Récursivité primitive"], ["Boolean algebra", "Predicate calculus", "Primitive recursion"]],
  ["Quel langage théorique d'Iverson a inspiré J et K ?", "Which Iverson language inspired J and K?", "APL", "APL", ["FP de Backus", "Plankalkül", "Speedcoding"], ["Backus' FP", "Plankalkül", "Speedcoding"]],
  ["Quel hyperviseur de Stanford a été commercialisé sous le nom Xen ?", "Which Stanford hypervisor became Xen?", "Xen Project (Univ. Cambridge)", "Xen Project (Univ. Cambridge)", ["VMware", "VirtualBox", "Hyper-V"], ["VMware", "VirtualBox", "Hyper-V"]],
  // Histoire profonde du Web et des créateurs (12)
  ["Quel est le titre de la toute première vidéo uploadée sur YouTube ?", "What was the very first YouTube video?", "Me at the zoo", "Me at the zoo", ["Charlie Bit My Finger", "Evolution of Dance", "Numa Numa"], ["Charlie Bit My Finger", "Evolution of Dance", "Numa Numa"]],
  ["Qui a uploadé la première vidéo de YouTube en 2005 ?", "Who uploaded YouTube's first video in 2005?", "Jawed Karim", "Jawed Karim", ["Steve Chen", "Chad Hurley", "Susan Wojcicki"], ["Steve Chen", "Chad Hurley", "Susan Wojcicki"]],
  ["Quel photographe espagnol est l'auteur de la photo 'Distracted Boyfriend' ?", "Which Spanish photographer shot 'Distracted Boyfriend'?", "Antonio Guillem", "Antonio Guillem", ["Pedro Almodóvar", "Joan Cros", "Manuel Outumuro"], ["Pedro Almodóvar", "Joan Cros", "Manuel Outumuro"]],
  ["Quel est le vrai nom de l'auteur du mème 'Numa Numa' ?", "What's the real name of the original 'Numa Numa' guy?", "Gary Brolsma", "Gary Brolsma", ["Eduardo Saverin", "Howard Davies-Carr", "Tay Zonday"], ["Eduardo Saverin", "Howard Davies-Carr", "Tay Zonday"]],
  ["Quel cofondateur de Reddit s'est suicidé en 2013 après poursuites pour JSTOR ?", "Which Reddit co-founder died by suicide in 2013 after the JSTOR case?", "Aaron Swartz", "Aaron Swartz", ["Alexis Ohanian", "Steve Huffman", "Christopher Slowe"], ["Alexis Ohanian", "Steve Huffman", "Christopher Slowe"]],
  ["En quelle année AOL a-t-il acquis Time Warner pour 165 Md $ ?", "When did AOL acquire Time Warner for $165B?", "2000", "2000", ["1998", "2002", "2004"], ["1998", "2002", "2004"]],
  ["En quelle année Logan Paul a-t-il filmé la 'Suicide Forest' au Japon ?", "When did Logan Paul film the 'Suicide Forest' in Japan?", "2017", "2017", ["2015", "2018", "2019"], ["2015", "2018", "2019"]],
  ["Quel est le tout premier réseau social en ligne, lancé en 1997 ?", "Which 1997 site is widely considered the first online social network?", "SixDegrees.com", "SixDegrees.com", ["Friendster", "MySpace", "LiveJournal"], ["Friendster", "MySpace", "LiveJournal"]],
  ["Quel duo a fondé la chaîne YouTube Smosh en 2005 ?", "Which duo founded the YouTube channel Smosh in 2005?", "Anthony Padilla et Ian Hecox", "Anthony Padilla and Ian Hecox", ["Rhett et Link", "Phil et Dan", "Logan et Jake Paul"], ["Rhett and Link", "Phil and Dan", "Logan and Jake Paul"]],
  ["Quel forum a popularisé en 2008 les Rage Comics ?", "Which forum popularized Rage Comics around 2008?", "4chan", "4chan", ["Reddit", "Something Awful", "9GAG"], ["Reddit", "Something Awful", "9GAG"]],
  ["Quel développeur a créé l'extension de blocage de pubs uBlock Origin ?", "Who created the ad-blocker uBlock Origin?", "Raymond Hill", "Raymond Hill", ["Wladimir Palant", "Eyal Gruner", "Henrik Aasted Sørensen"], ["Wladimir Palant", "Eyal Gruner", "Henrik Aasted Sørensen"]],
  ["Quel pseudonyme a porté le mème 'Bad Luck Brian' dans la vraie vie ?", "What's the real name of 'Bad Luck Brian'?", "Kyle Craven", "Kyle Craven", ["Zeddie Little", "Laina Morris", "Maggie Goldenberger"], ["Zeddie Little", "Laina Morris", "Maggie Goldenberger"]],
];

export const WEB_QUESTIONS = buildCuratedCategory(
  "web",
  "web",
  [easy, medium, hard, expert],
);
