/**
 * Seed fixtures for the question bank.
 * Bilingual (FR + EN), mixed categories and difficulties.
 *
 * Run with: pnpm db:seed
 */

interface SeedQuestion {
  /** Stable id so re-running the seed upserts instead of duplicating */
  id: string;
  locale: "fr" | "en";
  category: string;
  difficulty: "easy" | "medium" | "hard" | "expert";
  prompt: string;
  choices: string[];
  /** 0-based index into `choices` */
  correctIndex: number;
  explanation?: string;
  timeLimit?: number;
}

export const QUESTIONS: SeedQuestion[] = [
  // ─── FR ─────────────────────────────────────────────────────────────
  {
    id: "fr-geo-001",
    locale: "fr",
    category: "geography",
    difficulty: "medium",
    prompt: "Quelle est la capitale de la Mongolie ?",
    choices: ["Astana", "Oulan-Bator", "Bichkek", "Tachkent"],
    correctIndex: 1,
  },
  {
    id: "fr-geo-002",
    locale: "fr",
    category: "geography",
    difficulty: "easy",
    prompt: "Quel fleuve traverse Paris ?",
    choices: ["La Loire", "Le Rhône", "La Seine", "La Garonne"],
    correctIndex: 2,
  },
  {
    id: "fr-geo-003",
    locale: "fr",
    category: "geography",
    difficulty: "hard",
    prompt: "Quel pays compte le plus grand nombre de fuseaux horaires ?",
    choices: ["Russie", "États-Unis", "France", "Chine"],
    correctIndex: 2,
    explanation: "La France couvre 12 fuseaux horaires grâce à ses territoires d'outre-mer.",
  },
  {
    id: "fr-geo-004",
    locale: "fr",
    category: "geography",
    difficulty: "medium",
    prompt: "Quel est le plus haut sommet d'Afrique ?",
    choices: ["Mont Kenya", "Kilimandjaro", "Atlas", "Mont Cameroun"],
    correctIndex: 1,
  },
  {
    id: "fr-hist-001",
    locale: "fr",
    category: "history",
    difficulty: "easy",
    prompt: "En quelle année est tombé le mur de Berlin ?",
    choices: ["1987", "1989", "1991", "1993"],
    correctIndex: 1,
  },
  {
    id: "fr-hist-002",
    locale: "fr",
    category: "history",
    difficulty: "medium",
    prompt: "Qui a peint la chapelle Sixtine ?",
    choices: ["Léonard de Vinci", "Raphaël", "Michel-Ange", "Le Caravage"],
    correctIndex: 2,
  },
  {
    id: "fr-hist-003",
    locale: "fr",
    category: "history",
    difficulty: "hard",
    prompt: "Quel empereur romain a fait construire le Colisée ?",
    choices: ["Néron", "Vespasien", "Hadrien", "Trajan"],
    correctIndex: 1,
  },
  {
    id: "fr-sci-001",
    locale: "fr",
    category: "science",
    difficulty: "easy",
    prompt: "Quelle est la formule chimique de l'eau ?",
    choices: ["CO2", "H2O", "O2", "NaCl"],
    correctIndex: 1,
  },
  {
    id: "fr-sci-002",
    locale: "fr",
    category: "science",
    difficulty: "medium",
    prompt: "Quelle planète est la plus proche du Soleil ?",
    choices: ["Vénus", "Mars", "Mercure", "Terre"],
    correctIndex: 2,
  },
  {
    id: "fr-sci-003",
    locale: "fr",
    category: "science",
    difficulty: "hard",
    prompt: "Quel est le métal liquide à température ambiante ?",
    choices: ["Plomb", "Mercure", "Sodium", "Étain"],
    correctIndex: 1,
  },
  {
    id: "fr-web-001",
    locale: "fr",
    category: "tech",
    difficulty: "medium",
    prompt: "Quel réseau social a été lancé en 2010 par Kevin Systrom ?",
    choices: ["Pinterest", "Instagram", "Snapchat", "TikTok"],
    correctIndex: 1,
  },
  {
    id: "fr-web-002",
    locale: "fr",
    category: "tech",
    difficulty: "easy",
    prompt: "Que signifie HTTP ?",
    choices: [
      "HyperText Transfer Protocol",
      "High Transfer Protocol",
      "Home Text Transfer Protocol",
      "Hyper Type Transfer Protocol",
    ],
    correctIndex: 0,
  },
  {
    id: "fr-web-003",
    locale: "fr",
    category: "tech",
    difficulty: "hard",
    prompt: "Quel langage est utilisé pour interroger les bases de données relationnelles ?",
    choices: ["XML", "SQL", "JSON", "YAML"],
    correctIndex: 1,
  },
  {
    id: "fr-sport-001",
    locale: "fr",
    category: "sport",
    difficulty: "easy",
    prompt: "Combien de Ballons d'Or possède Lionel Messi en 2024 ?",
    choices: ["6", "7", "8", "9"],
    correctIndex: 2,
  },
  {
    id: "fr-sport-002",
    locale: "fr",
    category: "sport",
    difficulty: "medium",
    prompt: "Dans quelle ville se sont tenus les JO d'été 2020 ?",
    choices: ["Pékin", "Tokyo", "Paris", "Rio"],
    correctIndex: 1,
  },
  {
    id: "fr-sport-003",
    locale: "fr",
    category: "sport",
    difficulty: "medium",
    prompt: "Quel sport pratique-t-on à Wimbledon ?",
    choices: ["Golf", "Cricket", "Tennis", "Rugby"],
    correctIndex: 2,
  },
  {
    id: "fr-art-001",
    locale: "fr",
    category: "art",
    difficulty: "easy",
    prompt: "Qui a peint la Joconde ?",
    choices: ["Van Gogh", "Léonard de Vinci", "Picasso", "Monet"],
    correctIndex: 1,
  },
  {
    id: "fr-art-002",
    locale: "fr",
    category: "art",
    difficulty: "medium",
    prompt: "Quel mouvement artistique est associé à Claude Monet ?",
    choices: ["Cubisme", "Surréalisme", "Impressionnisme", "Réalisme"],
    correctIndex: 2,
  },
  {
    id: "fr-cine-001",
    locale: "fr",
    category: "cinema",
    difficulty: "easy",
    prompt: "Qui a réalisé Pulp Fiction ?",
    choices: ["Scorsese", "Tarantino", "Spielberg", "Coppola"],
    correctIndex: 1,
  },
  {
    id: "fr-cine-002",
    locale: "fr",
    category: "cinema",
    difficulty: "medium",
    prompt: "Quel film a remporté l'Oscar du meilleur film en 2020 ?",
    choices: ["1917", "Joker", "Parasite", "Once Upon a Time in Hollywood"],
    correctIndex: 2,
  },

  // ─── EN ─────────────────────────────────────────────────────────────
  {
    id: "en-geo-001",
    locale: "en",
    category: "geography",
    difficulty: "medium",
    prompt: "What is the capital of Mongolia?",
    choices: ["Astana", "Ulaanbaatar", "Bishkek", "Tashkent"],
    correctIndex: 1,
  },
  {
    id: "en-geo-002",
    locale: "en",
    category: "geography",
    difficulty: "easy",
    prompt: "Which river flows through Paris?",
    choices: ["Loire", "Rhône", "Seine", "Garonne"],
    correctIndex: 2,
  },
  {
    id: "en-geo-003",
    locale: "en",
    category: "geography",
    difficulty: "hard",
    prompt: "Which country has the most time zones?",
    choices: ["Russia", "United States", "France", "China"],
    correctIndex: 2,
    explanation: "France spans 12 time zones thanks to its overseas territories.",
  },
  {
    id: "en-geo-004",
    locale: "en",
    category: "geography",
    difficulty: "medium",
    prompt: "What is the highest peak in Africa?",
    choices: ["Mount Kenya", "Kilimanjaro", "Atlas", "Mount Cameroon"],
    correctIndex: 1,
  },
  {
    id: "en-hist-001",
    locale: "en",
    category: "history",
    difficulty: "easy",
    prompt: "In what year did the Berlin Wall fall?",
    choices: ["1987", "1989", "1991", "1993"],
    correctIndex: 1,
  },
  {
    id: "en-hist-002",
    locale: "en",
    category: "history",
    difficulty: "medium",
    prompt: "Who painted the Sistine Chapel?",
    choices: ["Leonardo da Vinci", "Raphael", "Michelangelo", "Caravaggio"],
    correctIndex: 2,
  },
  {
    id: "en-hist-003",
    locale: "en",
    category: "history",
    difficulty: "hard",
    prompt: "Which Roman emperor commissioned the Colosseum?",
    choices: ["Nero", "Vespasian", "Hadrian", "Trajan"],
    correctIndex: 1,
  },
  {
    id: "en-sci-001",
    locale: "en",
    category: "science",
    difficulty: "easy",
    prompt: "What is the chemical formula of water?",
    choices: ["CO2", "H2O", "O2", "NaCl"],
    correctIndex: 1,
  },
  {
    id: "en-sci-002",
    locale: "en",
    category: "science",
    difficulty: "medium",
    prompt: "Which planet is closest to the Sun?",
    choices: ["Venus", "Mars", "Mercury", "Earth"],
    correctIndex: 2,
  },
  {
    id: "en-sci-003",
    locale: "en",
    category: "science",
    difficulty: "hard",
    prompt: "Which metal is liquid at room temperature?",
    choices: ["Lead", "Mercury", "Sodium", "Tin"],
    correctIndex: 1,
  },
  {
    id: "en-web-001",
    locale: "en",
    category: "tech",
    difficulty: "medium",
    prompt: "Which social network did Kevin Systrom launch in 2010?",
    choices: ["Pinterest", "Instagram", "Snapchat", "TikTok"],
    correctIndex: 1,
  },
  {
    id: "en-web-002",
    locale: "en",
    category: "tech",
    difficulty: "easy",
    prompt: "What does HTTP stand for?",
    choices: [
      "HyperText Transfer Protocol",
      "High Transfer Protocol",
      "Home Text Transfer Protocol",
      "Hyper Type Transfer Protocol",
    ],
    correctIndex: 0,
  },
  {
    id: "en-web-003",
    locale: "en",
    category: "tech",
    difficulty: "hard",
    prompt: "Which language is used to query relational databases?",
    choices: ["XML", "SQL", "JSON", "YAML"],
    correctIndex: 1,
  },
  {
    id: "en-sport-001",
    locale: "en",
    category: "sport",
    difficulty: "easy",
    prompt: "How many Ballon d'Or has Lionel Messi won as of 2024?",
    choices: ["6", "7", "8", "9"],
    correctIndex: 2,
  },
  {
    id: "en-sport-002",
    locale: "en",
    category: "sport",
    difficulty: "medium",
    prompt: "Which city hosted the 2020 Summer Olympics?",
    choices: ["Beijing", "Tokyo", "Paris", "Rio"],
    correctIndex: 1,
  },
  {
    id: "en-sport-003",
    locale: "en",
    category: "sport",
    difficulty: "medium",
    prompt: "What sport is played at Wimbledon?",
    choices: ["Golf", "Cricket", "Tennis", "Rugby"],
    correctIndex: 2,
  },
  {
    id: "en-art-001",
    locale: "en",
    category: "art",
    difficulty: "easy",
    prompt: "Who painted the Mona Lisa?",
    choices: ["Van Gogh", "Leonardo da Vinci", "Picasso", "Monet"],
    correctIndex: 1,
  },
  {
    id: "en-art-002",
    locale: "en",
    category: "art",
    difficulty: "medium",
    prompt: "Which art movement is Claude Monet associated with?",
    choices: ["Cubism", "Surrealism", "Impressionism", "Realism"],
    correctIndex: 2,
  },
  {
    id: "en-cine-001",
    locale: "en",
    category: "cinema",
    difficulty: "easy",
    prompt: "Who directed Pulp Fiction?",
    choices: ["Scorsese", "Tarantino", "Spielberg", "Coppola"],
    correctIndex: 1,
  },
  {
    id: "en-cine-002",
    locale: "en",
    category: "cinema",
    difficulty: "medium",
    prompt: "Which film won Best Picture at the 2020 Oscars?",
    choices: ["1917", "Joker", "Parasite", "Once Upon a Time in Hollywood"],
    correctIndex: 2,
  },
];

export type { SeedQuestion };
